(function(){'use strict';const U=AlumniUI,skills=['Java','Spring Boot','Python','AI','빅데이터','클라우드','Docker','Kubernetes','DevOps','데이터베이스','프론트엔드'],topics=['취업 준비','회사 정보','직무 상담','개발 공부','AI','빅데이터','클라우드','대학원 진학','자격증','포트폴리오','면접','기타'];let authPin='';
function checks(name,vals){U.qs(`[data-checks="${name}"]`).innerHTML=vals.map(v=>`<label class="check"><input type="checkbox" name="${name}" value="${v}">${v}</label>`).join('')}
function addBachelorEnrollmentOption(){const select=U.qs('[name="bachelor_status"]');if(select&&!U.qs('option[value="재학"]',select)){const option=document.createElement('option');option.value='재학';option.textContent='재학';select.insertBefore(option,select.options[1]||null)}}
function addGraduatePreparationOption(){const select=U.qs('[name="graduate_status"]');if(select&&!Array.from(select.options).some(option=>option.value==='진학 예정(준비중)')){const option=document.createElement('option');option.value='진학 예정(준비중)';option.textContent='진학 예정(준비중)';select.insertBefore(option,select.options[2]||null)}}
function addResearchLabOptions(){const select=U.qs('[name="employment_status"]');['대학원 연구실(석사과정)','대학원 연구실(박사과정)'].forEach(value=>{if(!Array.from(select.options).some(option=>option.value===value)){const option=document.createElement('option');option.value=value;option.textContent=value;select.insertBefore(option,select.options[2]||null)}})}
function conditional(select,box,predicate,requiredNames=[]){const s=U.qs(`[name="${select}"]`),b=U.qs(box);function sync(){const on=predicate(s.value);b.hidden=!on;requiredNames.forEach(n=>{const x=U.qs(`[name="${n}"]`);if(x)x.required=on})}s.addEventListener('change',sync);sync()}
function values(form){const o=Object.fromEntries(new FormData(form));['skills','mentoring_topics'].forEach(n=>o[n]=U.qsa(`[name="${n}"]:checked`).map(x=>x.value));if(o.skills_other)o.skills.push(...o.skills_other.split(',').map(x=>x.trim()).filter(Boolean));['privacy_consent','identity_consent','contact_consent'].forEach(n=>o[n]=Boolean(U.qs(`[name="${n}"]`)?.checked));return o}
function fill(a){Object.entries(a).forEach(([k,v])=>{const nodes=U.qsa(`[name="${k}"]`);if(!nodes.length)return;if(nodes[0].type==='checkbox'){const arr=Array.isArray(v)?v:String(v||'').split('|');nodes.forEach(n=>n.checked=arr.includes(n.value))}else nodes[0].value=v??''});U.qs('[name="privacy_consent"]').checked=true;U.qs('[name="identity_consent"]').checked=true;U.qs('[name="employment_status"]').dispatchEvent(new Event('change'));U.qs('[name="bachelor_status"]').dispatchEvent(new Event('change'));U.qs('[name="graduate_status"]').dispatchEvent(new Event('change'));U.qs('[name="contact_allowed"]').dispatchEvent(new Event('change'))}
document.addEventListener('DOMContentLoaded',()=>{const form=U.qs('#alumni-form'),st=U.qs('#form-status'),btn=U.qs('#alumni-submit'),activeEmployment=['취업 중','대학원 연구실(석사과정)','대학원 연구실(박사과정)'];U.yearOptions(U.qs('#form-graduation-year'));checks('skills',skills);checks('mentoring_topics',topics);addBachelorEnrollmentOption();addGraduatePreparationOption();addResearchLabOptions();conditional('employment_status','#employment-fields',v=>activeEmployment.includes(v),['company','job']);conditional('bachelor_status','#bachelor-fields',v=>v==='재학'||v==='취득'||v==='취득 예정');conditional('graduate_status','#graduate-fields',v=>['재학','휴학','수료','졸업'].includes(v),['graduate_school_type','graduate_school','graduate_major']);conditional('contact_allowed','#mentoring-fields',v=>v==='true');
function mode(edit){U.qs('#register-tab').setAttribute('aria-selected',String(!edit));U.qs('#edit-tab').setAttribute('aria-selected',String(edit));U.qs('#lookup-panel').hidden=!edit;form.hidden=edit;form.reset();U.qs('[name="mode"]').value=edit?'update':'register';U.qs('[name="edit_pin"]').required=!edit;btn.textContent=edit?'정보 수정하기':'등록 신청하기';st.hidden=true}U.qs('#register-tab').onclick=()=>mode(false);U.qs('#edit-tab').onclick=()=>mode(true);
U.qs('#lookup-button').onclick=async()=>{const id=U.qs('#lookup-id').value.trim(),pin=U.qs('#lookup-pin').value;if(!id||!/^\d{6,12}$/.test(pin)){U.status(st,'Alumni ID와 숫자 6~12자리 PIN을 확인해 주세요.','error');return}const b=U.qs('#lookup-button');U.busy(b,true,'확인 중…');try{const r=await AlumniAPI.request('getOwn',{method:'POST',data:{alumni_id:id,edit_pin:pin}});authPin=pin;fill(r.data);U.qs('[name="alumni_id"]').value=id;form.hidden=false;U.qs('#lookup-panel').hidden=true;U.status(st,'본인 확인이 완료되었습니다. 정보를 수정해 주세요.','success')}catch(e){U.status(st,e.message,'error')}finally{U.busy(b,false)}};
form.onsubmit=async e=>{e.preventDefault();if(!form.reportValidity())return;const data=values(form),action=data.mode==='update'?'update':'register';if(action==='update')data.auth_pin=authPin;if(data.contact_allowed==='true'&&!data.contact_consent){U.status(st,'연락 요청을 허용하려면 연락 요청 수신 동의가 필요합니다.','error');return}U.busy(btn,true,action==='update'?'수정 중…':'등록 중…');try{const r=await AlumniAPI.request(action,{method:'POST',data});form.reset();form.hidden=true;U.status(st,action==='register'?`정보 등록이 완료되었습니다. 관리자 확인 후 공개됩니다. Alumni ID: ${r.alumni_id}`:'정보가 수정되었습니다.','success')}catch(err){U.status(st,err.message,'error')}finally{U.busy(btn,false)}}})})();
