window.ALUMNI_CONFIG = Object.freeze({
  API_URL: 'PASTE_YOUR_GOOGLE_APPS_SCRIPT_WEB_APP_URL_HERE',
  GOOGLE_CLIENT_ID: 'PASTE_YOUR_GOOGLE_OAUTH_CLIENT_ID_HERE',
  SITE_URL: 'https://alumni.k-bigdata.kr',
  REQUEST_TIMEOUT_MS: 15000
});
