'use strict';
const SHEETS={ALUMNI:'alumni',CONTACTS:'contact_requests',ADMINS:'admins',LOGS:'logs',JOBS:'jobs',JOB_MAIL_LOGS:'job_mail_logs',CONSENT_LOGS:'alumni_consent_logs',CONSENT_INVITES:'career_consent_invites',NEWS:'alumni_news',NEWS_MAIL_LOGS:'alumni_news_mail_logs',NEWS_CONSENT_INVITES:'alumni_news_consent_invites'};
const ALUMNI_HEADERS=['alumni_id','name','student_id','graduation_year','email','phone','employment_status','company','job','company_url','employment_year','job_description','skills','bachelor_status','bachelor_school','bachelor_major','bachelor_year','graduate_status','graduate_school_type','graduate_school','graduate_major','graduate_degree','graduate_entry_year','graduate_graduation_year','research_fields','mentoring_topics','introduction','message_to_juniors','contact_allowed','edit_pin_hash','status','created_at','updated_at','career_mail_enabled','career_mail_consent_at','career_mail_updated_at','alumni_news_mail_enabled','alumni_news_mail_consent_at','alumni_news_mail_updated_at'];
const CONTACT_HEADERS=['request_id','alumni_id','requester_name','requester_type','requester_student_id_or_year','requester_email','requester_phone','share_email','share_phone','category','subject','message','status','created_at','sent_at'];
const ADMIN_HEADERS=['email','status','created_at'];
const LOG_HEADERS=['log_id','action','result','reference_id','detail','created_at'];
const JOB_HEADERS=['job_id','alumni_id','company','job_title','recruit_type','employment_type','location','job_url','deadline','always_open','skills','alumni_comment','referral_available','contact_allowed','status','approved_at','approved_by','created_at','updated_at','last_mailed_at','approval_nonce_hash','approval_token_expires_at'];
const JOB_MAIL_LOG_HEADERS=['mail_id','job_ids','recipient_count','sent_count','failed_count','sent_at','status'];
const CONSENT_LOG_HEADERS=['log_id','alumni_id','consent_type','previous_value','new_value','changed_at'];
const CONSENT_INVITE_HEADERS=['invite_id','alumni_id','sent_at','status'];
const NEWS_HEADERS=['news_id','alumni_id','submitted_by_alumni_id','news_type','title','content','company','job_title','organization','position_title','school_name','degree_or_program','event_date','location','relationship','external_url','mail_requested','mail_status','status','approved_at','approved_by','created_at','updated_at','approval_nonce_hash','approval_token_expires_at'];
const NEWS_MAIL_LOG_HEADERS=['mail_id','news_id','news_type','subject','recipient_count','sent_count','failed_count','sent_at','status'];
const NEWS_CONSENT_INVITE_HEADERS=['invite_id','alumni_id','sent_at','status'];
const NEWS_TYPES=['EMPLOYMENT','JOB_CHANGE','PROMOTION','STARTUP','GRADUATE_SCHOOL','ACHIEVEMENT','MARRIAGE','BIRTH_SON','BIRTH_DAUGHTER','OBITUARY','OTHER'];
const NEWS_LABELS={EMPLOYMENT:'취업',JOB_CHANGE:'이직',PROMOTION:'승진·보직',STARTUP:'창업',GRADUATE_SCHOOL:'대학원·학위',ACHIEVEMENT:'수상·성과',MARRIAGE:'결혼',BIRTH_SON:'득남',BIRTH_DAUGHTER:'득녀',OBITUARY:'부고',OTHER:'기타'};
const PUBLIC_FIELDS=['alumni_id','name','graduation_year','employment_status','company','job','company_url','employment_year','job_description','skills','bachelor_status','bachelor_school','bachelor_major','bachelor_year','graduate_status','graduate_school_type','graduate_school','graduate_major','graduate_degree','graduate_entry_year','graduate_graduation_year','research_fields','mentoring_topics','introduction','message_to_juniors','contact_allowed','updated_at'];
const ENUMS={employment_status:['취업 중','대학원 준비중','대학원 연구실(석사과정)','대학원 연구실(박사과정)','구직 중','미취업','기타'],bachelor_status:['재학','취득','취득 예정','미취득'],graduate_status:['진학하지 않음','진학 예정(준비중)','재학','휴학','수료','졸업'],graduate_school_type:['일반대학원','전문대학원','특수대학원'],graduate_degree:['','석사','박사','석박사통합'],requester_type:['재학생','졸업생'],recruit_type:['신입','경력','신입·경력'],employment_type:['정규직','계약직','인턴','기타']};

function doGet(e){const p=e.parameter||{},action=String(p.action||'');try{if(action==='approveByEmail')return approveByEmail_(p.token);if(action==='moderateJob')return moderateJobByEmail_(p.token);if(action==='moderateNews')return moderateNewsByEmail_(p.token);return respond_(routeGet_(action,p));}catch(err){log_('get','FAILED','',err.message);if(['approveByEmail','moderateJob','moderateNews'].includes(action))return approvalPage_('처리 실패',safeError_(err),false);return respond_({success:false,message:safeError_(err)});}}
function doPost(e){let body={};try{body=JSON.parse((e.postData&&e.postData.contents)||'{}');return respond_(routePost_(String(body.action||''),body));}catch(err){log_('post','FAILED','',err.message);return respond_({success:false,message:safeError_(err)});}}
function routeGet_(action,p){if(action==='list')return {success:true,data:listPublic_()};if(action==='detail')return {success:true,data:detailPublic_(p.id)};if(action==='jobs')return {success:true,data:listJobsPublic_()};if(action==='jobDetail')return {success:true,data:jobDetailPublic_(p.id)};if(action==='alumniJobs')return {success:true,data:alumniJobsPublic_(p.id)};if(action==='newsList')return {success:true,data:listNewsPublic_()};if(action==='newsDetail')return {success:true,data:newsDetailPublic_(p.id)};if(action==='alumniNews')return {success:true,data:alumniNewsPublic_(p.id)};throw new Error('지원하지 않는 요청입니다.');}
function routePost_(action,b){if(action==='register')return register_(b);if(action==='getOwn')return getOwn_(b);if(action==='update')return update_(b);if(action==='contact')return contact_(b);if(action==='verifyJobAlumni')return verifyJobAlumni_(b);if(action==='submitJob')return submitJob_(b);if(action==='verifyNewsAlumni')return verifyNewsAlumni_(b);if(action==='submitNews')return submitNews_(b);if(action==='newsAlumniSearch')return newsAlumniSearch_(b);if(action==='adminList')return adminList_(b);if(['adminApprove','adminReject','adminHide'].indexOf(action)>=0)return adminStatus_(action,b);if(['adminJobApprove','adminJobReject','adminJobHide','adminJobPublish'].includes(action))return adminJobStatus_(action,b);if(['adminNewsApproveAndMail','adminNewsApprove','adminNewsReject','adminNewsHide','adminNewsPublish'].includes(action))return adminNewsStatus_(action,b);if(action==='adminCreateNews')return adminCreateNews_(b);if(action==='adminSendCareerConsentInvites')return adminSendCareerConsentInvites_(b);if(action==='adminSendNewsConsentInvites')return adminSendNewsConsentInvites_(b);if(action==='adminRunJobDigest')return adminRunJobDigest_(b);throw new Error('지원하지 않는 요청입니다.');}
function respond_(obj){return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON);}
function safeError_(e){const allowed=['지원하지','찾을 수','입력','형식','필수','PIN','Alumni','권한','요청','허용','중복','길이','동의','설정','승인','채용정보','URL','마감일','만료'];return allowed.some(x=>String(e.message).includes(x))?e.message:'처리 중 오류가 발생했습니다.';}

function setup(){migrateJobsFeature();migrateAlumniNewsFeature();const props=PropertiesService.getScriptProperties();if(!props.getProperty('PIN_PEPPER'))props.setProperty('PIN_PEPPER',Utilities.getUuid()+Utilities.getUuid());}
function migrateJobsFeature(){const ss=db_();ensure_(ss,SHEETS.ALUMNI,ALUMNI_HEADERS);ensure_(ss,SHEETS.CONTACTS,CONTACT_HEADERS);ensure_(ss,SHEETS.ADMINS,ADMIN_HEADERS);ensure_(ss,SHEETS.LOGS,LOG_HEADERS);ensure_(ss,SHEETS.JOBS,JOB_HEADERS);ensure_(ss,SHEETS.JOB_MAIL_LOGS,JOB_MAIL_LOG_HEADERS);ensure_(ss,SHEETS.CONSENT_LOGS,CONSENT_LOG_HEADERS);ensure_(ss,SHEETS.CONSENT_INVITES,CONSENT_INVITE_HEADERS);return '채용정보 기능용 시트와 누락 컬럼을 안전하게 추가했습니다.';}
function migrateAlumniNewsFeature(){const ss=db_();ensure_(ss,SHEETS.ALUMNI,ALUMNI_HEADERS);ensure_(ss,SHEETS.CONSENT_LOGS,CONSENT_LOG_HEADERS);ensure_(ss,SHEETS.NEWS,NEWS_HEADERS);ensure_(ss,SHEETS.NEWS_MAIL_LOGS,NEWS_MAIL_LOG_HEADERS);ensure_(ss,SHEETS.NEWS_CONSENT_INVITES,NEWS_CONSENT_INVITE_HEADERS);return '동문소식 기능용 시트와 누락 컬럼을 안전하게 추가했습니다.';}
function ensure_(ss,name,headers){let sh=ss.getSheetByName(name);if(!sh)sh=ss.insertSheet(name);if(sh.getLastRow()===0){sh.appendRow(headers);sh.setFrozenRows(1);return;}const width=Math.max(1,sh.getLastColumn()),got=sh.getRange(1,1,1,width).getValues()[0].map(String);for(let i=0;i<got.length;i++){if(headers[i]!==got[i])throw new Error(name+' 시트의 기존 헤더 순서가 다릅니다: '+got[i]);}if(headers.length>got.length)sh.getRange(1,got.length+1,1,headers.length-got.length).setValues([headers.slice(got.length)]);sh.setFrozenRows(1);}
function db_(){const id=PropertiesService.getScriptProperties().getProperty('SPREADSHEET_ID');if(!id)throw new Error('SPREADSHEET_ID 설정이 필요합니다.');return SpreadsheetApp.openById(id);}
function sheet_(name){const sh=db_().getSheetByName(name);if(!sh)throw new Error('데이터 저장소가 설정되지 않았습니다. setup을 실행해 주세요.');return sh;}
function rows_(name,headers){const sh=sheet_(name);if(sh.getLastRow()<2)return[];return sh.getRange(2,1,sh.getLastRow()-1,headers.length).getValues().map((r,i)=>Object.assign({__row:i+2},Object.fromEntries(headers.map((h,j)=>[h,r[j]]))));}
function prepareTextColumns_(sh,headers,row){['phone','requester_phone'].forEach(k=>{const i=headers.indexOf(k);if(i>=0)sh.getRange(row,i+1).setNumberFormat('@');});}
function append_(name,headers,obj){const sh=sheet_(name),row=sh.getLastRow()+1;prepareTextColumns_(sh,headers,row);sh.getRange(row,1,1,headers.length).setValues([headers.map(h=>obj[h]===undefined?'':obj[h])]);}
function updateRow_(name,headers,row,obj){const sh=sheet_(name);prepareTextColumns_(sh,headers,row);sh.getRange(row,1,1,headers.length).setValues([headers.map(h=>obj[h]===undefined?'':obj[h])]);}
function now_(){return Utilities.formatDate(new Date(),'Asia/Seoul',"yyyy-MM-dd'T'HH:mm:ssXXX");}
function id_(prefix){return prefix+'-'+Utilities.formatDate(new Date(),'Asia/Seoul','yyyyMMdd')+'-'+Utilities.getUuid().slice(0,8).toUpperCase();}
function findAlumni_(id){return rows_(SHEETS.ALUMNI,ALUMNI_HEADERS).find(x=>String(x.alumni_id)===String(id));}
function public_(x){return Object.fromEntries(PUBLIC_FIELDS.map(k=>[k,normalizeOut_(k,x[k])]));}
function normalizeOut_(key,v){if(['skills','research_fields','mentoring_topics'].includes(key))return String(v||'').split('|').filter(Boolean);if(key==='contact_allowed')return String(v).toLowerCase()==='true';if(['career_mail_enabled','alumni_news_mail_enabled'].includes(key))return String(v)===''?'':String(v).toLowerCase()==='true';if(v instanceof Date)return Utilities.formatDate(v,'Asia/Seoul',"yyyy-MM-dd'T'HH:mm:ssXXX");return v===undefined?'':v;}
function listPublic_(){return rows_(SHEETS.ALUMNI,ALUMNI_HEADERS).filter(x=>x.status==='APPROVED').map(public_);}
function detailPublic_(id){const x=findAlumni_(clean_(id,40));if(!x||x.status!=='APPROVED')throw new Error('졸업생 정보를 찾을 수 없습니다.');return public_(x);}

function register_(b){validateAlumni_(b,true);const lock=LockService.getScriptLock();lock.waitLock(10000);let obj;try{const now=now_(),id=id_('A');obj=alumniObject_(b);Object.assign(obj,{alumni_id:id,edit_pin_hash:hashPin_(id,b.edit_pin),status:'PENDING',created_at:now,updated_at:now,career_mail_enabled:bool_(b.career_mail_enabled),career_mail_consent_at:bool_(b.career_mail_enabled)?now:'',career_mail_updated_at:now,alumni_news_mail_enabled:bool_(b.alumni_news_mail_enabled),alumni_news_mail_consent_at:bool_(b.alumni_news_mail_enabled)?now:'',alumni_news_mail_updated_at:now});append_(SHEETS.ALUMNI,ALUMNI_HEADERS,obj);appendConsentLog_(id,'',String(bool_(b.career_mail_enabled)).toUpperCase());appendConsentLog_(id,'',String(bool_(b.alumni_news_mail_enabled)).toUpperCase(),'ALUMNI_NEWS_MAIL');log_('register','SUCCESS',id,'PENDING');}finally{lock.releaseLock();}try{sendApprovalMail_(obj);}catch(e){log_('approvalMail','FAILED',obj.alumni_id,e.message);}return{success:true,message:'정보 등록이 완료되었습니다. 관리자 확인 후 공개됩니다.',alumni_id:obj.alumni_id};}
function getOwn_(b){const id=clean_(b.alumni_id,40),x=findAlumni_(id);if(!x||!verifyPin_(id,b.edit_pin,x.edit_pin_hash))throw new Error('Alumni ID 또는 PIN이 올바르지 않습니다.');const out=Object.fromEntries(ALUMNI_HEADERS.filter(k=>!['edit_pin_hash'].includes(k)).map(k=>[k,normalizeOut_(k,x[k])]));return{success:true,data:out};}
function update_(b){validateAlumni_(b,false);const id=clean_(b.alumni_id,40),lock=LockService.getScriptLock();lock.waitLock(10000);try{const x=findAlumni_(id);if(!x||!verifyPin_(id,b.auth_pin,x.edit_pin_hash))throw new Error('Alumni ID 또는 PIN이 올바르지 않습니다.');const now=now_(),before=String(x.career_mail_enabled),after=String(bool_(b.career_mail_enabled)).toUpperCase(),changed=before.toUpperCase()!==after,newsBefore=String(x.alumni_news_mail_enabled),newsAfter=String(bool_(b.alumni_news_mail_enabled)).toUpperCase(),newsChanged=newsBefore.toUpperCase()!==newsAfter;const obj=Object.assign({},x,alumniObject_(b),{alumni_id:id,edit_pin_hash:x.edit_pin_hash,status:'PENDING',created_at:x.created_at,updated_at:now,career_mail_enabled:bool_(b.career_mail_enabled),career_mail_consent_at:bool_(b.career_mail_enabled)?(x.career_mail_consent_at||now):'',career_mail_updated_at:changed?now:x.career_mail_updated_at,alumni_news_mail_enabled:bool_(b.alumni_news_mail_enabled),alumni_news_mail_consent_at:bool_(b.alumni_news_mail_enabled)?(x.alumni_news_mail_consent_at||now):'',alumni_news_mail_updated_at:newsChanged?now:x.alumni_news_mail_updated_at});if(b.edit_pin)obj.edit_pin_hash=hashPin_(id,b.edit_pin);delete obj.__row;updateRow_(SHEETS.ALUMNI,ALUMNI_HEADERS,x.__row,obj);if(changed)appendConsentLog_(id,before,after);if(newsChanged)appendConsentLog_(id,newsBefore,newsAfter,'ALUMNI_NEWS_MAIL');log_('update','SUCCESS',id,'PENDING');return{success:true,message:'정보가 수정되었습니다. 관리자 재승인 후 공개됩니다.'};}finally{lock.releaseLock();}}
function alumniObject_(b){const obj={};ALUMNI_HEADERS.forEach(k=>{if(['alumni_id','edit_pin_hash','status','created_at','updated_at','career_mail_enabled','career_mail_consent_at','career_mail_updated_at','alumni_news_mail_enabled','alumni_news_mail_consent_at','alumni_news_mail_updated_at'].includes(k))return;obj[k]=['skills','research_fields','mentoring_topics'].includes(k)?list_(b[k],300):clean_(b[k],limit_(k));});obj.phone=phoneText_(obj.phone);obj.contact_allowed=bool_(b.contact_allowed);if(!['취업 중','대학원 연구실(석사과정)','대학원 연구실(박사과정)'].includes(obj.employment_status)){['company','job','company_url','employment_year','job_description','skills'].forEach(k=>obj[k]='');}if(obj.bachelor_status==='미취득'){['bachelor_school','bachelor_major','bachelor_year'].forEach(k=>obj[k]='');}if(['진학하지 않음','진학 예정(준비중)'].includes(obj.graduate_status)){['graduate_school_type','graduate_school','graduate_major','graduate_degree','graduate_entry_year','graduate_graduation_year','research_fields'].forEach(k=>obj[k]='');}return obj;}
function appendConsentLog_(alumniId,before,after,type){append_(SHEETS.CONSENT_LOGS,CONSENT_LOG_HEADERS,{log_id:id_('C'),alumni_id:alumniId,consent_type:type||'CAREER_MAIL',previous_value:before,new_value:after,changed_at:now_()});}
function validateAlumni_(b,isNew){required_(b,['name','graduation_year','email','phone','employment_status','bachelor_status','graduate_status','contact_allowed']);if(!email_(b.email))throw new Error('이메일 형식을 확인해 주세요.');if(!phone_(b.phone))throw new Error('휴대전화 형식을 확인해 주세요.');enum_(b,'employment_status');enum_(b,'bachelor_status');enum_(b,'graduate_status');if(['취업 중','대학원 연구실(석사과정)','대학원 연구실(박사과정)'].includes(b.employment_status))required_(b,['company','job']);if(['재학','휴학','수료','졸업'].includes(b.graduate_status)){required_(b,['graduate_school_type','graduate_school','graduate_major']);enum_(b,'graduate_school_type');if(b.graduate_degree)enum_(b,'graduate_degree');}if(bool_(b.contact_allowed)&&!list_(b.mentoring_topics,300))throw new Error('연락 요청을 허용하려면 상담 가능 분야를 1개 이상 선택해 주세요.');if(!bool_(b.privacy_consent)||!bool_(b.identity_consent))throw new Error('필수 개인정보 동의가 필요합니다.');if(bool_(b.contact_allowed)&&!bool_(b.contact_consent))throw new Error('연락 요청 수신 동의가 필요합니다.');if((isNew||b.edit_pin)&&!/^\d{6,12}$/.test(String(b.edit_pin||'')))throw new Error('PIN은 숫자 6~12자리여야 합니다.');}

function contact_(b){required_(b,['alumni_id','requester_name','requester_type','requester_email','category','subject','message']);if(b.website)throw new Error('요청을 처리할 수 없습니다.');if(!email_(b.requester_email))throw new Error('이메일 형식을 확인해 주세요.');if(b.requester_phone&&!phone_(b.requester_phone))throw new Error('휴대전화 형식을 확인해 주세요.');enum_(b,'requester_type');if(String(b.message).trim().length<20)throw new Error('문의 내용은 20자 이상 입력해 주세요.');if(bool_(b.share_phone)&&!b.requester_phone)throw new Error('전달할 휴대전화를 입력해 주세요.');const alum=findAlumni_(clean_(b.alumni_id,40));if(!alum||alum.status!=='APPROVED'||!bool_(alum.contact_allowed))throw new Error('현재 연락 요청을 허용하지 않는 졸업생입니다.');let job=null;if(b.job_id){job=findJob_(clean_(b.job_id,40));if(!job||job.status!=='APPROVED'||job.alumni_id!==alum.alumni_id||!bool_(job.contact_allowed))throw new Error('문의할 채용정보를 찾을 수 없거나 문의가 허용되지 않았습니다.');}rateLimit_(alum.alumni_id+(job?'|'+job.job_id:''),b.requester_email);const lock=LockService.getScriptLock();lock.waitLock(10000);const now=now_(),rid=id_('R'),jobNote=job?'[채용공고 '+job.job_id+' · '+job.company+' · '+job.job_title+']\n':'',obj={request_id:rid,alumni_id:alum.alumni_id,requester_name:clean_(b.requester_name,40),requester_type:clean_(b.requester_type,10),requester_student_id_or_year:clean_(b.requester_student_id_or_year,30),requester_email:clean_(b.requester_email,120),requester_phone:phoneText_(b.requester_phone),share_email:bool_(b.share_email),share_phone:bool_(b.share_phone),category:clean_(b.category,40),subject:clean_(b.subject,100),message:jobNote+clean_(b.message,1500),status:'PENDING',created_at:now,sent_at:''};append_(SHEETS.CONTACTS,CONTACT_HEADERS,obj);lock.releaseLock();try{MailApp.sendEmail({to:String(alum.email),subject:'[BigData Alumni] '+(job?'채용정보 ':'')+'문의가 도착했습니다',htmlBody:mailHtml_(alum,obj,job),name:'BigData Alumni Network'});obj.status='SENT';obj.sent_at=now_();updateContact_(rid,obj);log_('contact','SUCCESS',rid,alum.alumni_id);return{success:true,message:'연락 요청이 정상적으로 전달되었습니다.'};}catch(e){obj.status='FAILED';updateContact_(rid,obj);log_('contact','FAILED',rid,e.message);throw new Error('메일 발송 중 오류가 발생했습니다. 잠시 후 다시 시도해 주세요.');}}
function rateLimit_(aid,email){const key=Utilities.base64EncodeWebSafe(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,aid+'|'+String(email).toLowerCase())).slice(0,80),cache=CacheService.getScriptCache();if(cache.get(key))throw new Error('동일한 선배에게 짧은 시간 내 중복 요청할 수 없습니다.');const cutoff=Date.now()-30*60*1000,dup=rows_(SHEETS.CONTACTS,CONTACT_HEADERS).some(x=>x.alumni_id===aid&&String(x.requester_email).toLowerCase()===String(email).toLowerCase()&&new Date(x.created_at).getTime()>cutoff);if(dup)throw new Error('동일한 선배에게 짧은 시간 내 중복 요청할 수 없습니다.');cache.put(key,'1',1800);}
function updateContact_(id,obj){const x=rows_(SHEETS.CONTACTS,CONTACT_HEADERS).find(r=>r.request_id===id);if(x)updateRow_(SHEETS.CONTACTS,CONTACT_HEADERS,x.__row,obj);}
function mailHtml_(a,r,job){const e=html_;let contacts=[];if(r.share_email)contacts.push('이메일: '+e(r.requester_email));if(r.share_phone)contacts.push('휴대전화: '+e(r.requester_phone));const jobBox=job?`<div style="background:#eaf4fb;padding:16px;border-radius:10px;margin-bottom:16px"><b>문의 채용공고</b><p style="margin-bottom:0">${e(job.company)} · ${e(job.job_title)}<br><span style="font-size:12px;color:#627d98">${e(job.job_id)}</span></p></div>`:'';return `<div style="font-family:Arial,sans-serif;max-width:640px;color:#243b53"><h2 style="color:#102a43">BigData Alumni Network</h2><p>안녕하세요. ${e(a.name)} 졸업생님.</p><p>한국폴리텍대학 서울강서캠퍼스 빅데이터소프트웨어공학과 Alumni Network를 통해 연락 요청이 접수되었습니다.</p>${jobBox}<div style="background:#f3f7fa;padding:16px;border-radius:10px"><b>요청자 정보</b><p>${e(r.requester_name)} · ${e(r.requester_type)}<br>${e(r.requester_student_id_or_year)}</p><b>문의 분야</b><p>${e(r.category)}</p><b>문의 제목</b><p>${e(r.subject)}</p><b>문의 내용</b><p style="white-space:pre-wrap">${e(r.message)}</p><b>연락처</b><p>${contacts.length?contacts.join('<br>'):'공개를 선택한 연락처가 없습니다.'}</p></div><p style="font-size:12px;color:#627d98">본 메일은 BigData Alumni Network를 통해 자동 발송되었습니다.</p></div>`;}

function findJob_(id){return rows_(SHEETS.JOBS,JOB_HEADERS).find(x=>String(x.job_id)===String(id));}
function dateOnly_(v){if(!v)return'';if(v instanceof Date)return Utilities.formatDate(v,'Asia/Seoul','yyyy-MM-dd');const s=String(v).trim();return /^\d{4}-\d{2}-\d{2}$/.test(s)?s:'';}
function url_(v){const s=String(v||'').trim();return /^https?:\/\/[A-Za-z0-9.-]+(?::\d+)?(?:[/?#][^\s]*)?$/i.test(s)?s:'';}
function maskName_(v){const a=Array.from(String(v||''));return a.length<2?'○':a[0]+'○'.repeat(Math.max(1,a.length-1));}
function isOpenJob_(j){return j.status==='APPROVED'&&(bool_(j.always_open)||!dateOnly_(j.deadline)||dateOnly_(j.deadline)>=Utilities.formatDate(new Date(),'Asia/Seoul','yyyy-MM-dd'));}
function jobPublic_(j){const a=findAlumni_(j.alumni_id)||{};return{job_id:String(j.job_id),alumni_id:String(j.alumni_id),company:String(j.company||''),job_title:String(j.job_title||''),recruit_type:String(j.recruit_type||''),employment_type:String(j.employment_type||''),location:String(j.location||''),job_url:String(j.job_url||''),deadline:dateOnly_(j.deadline),always_open:bool_(j.always_open),skills:String(j.skills||'').split('|').filter(Boolean),alumni_comment:String(j.alumni_comment||''),referral_available:bool_(j.referral_available),contact_allowed:bool_(j.contact_allowed)&&bool_(a.contact_allowed),created_at:normalizeOut_('',j.created_at),alumni_name:maskName_(a.name),graduation_year:String(a.graduation_year||''),alumni_job:String(a.job||'')};}
function listJobsPublic_(){expireJobs_();return rows_(SHEETS.JOBS,JOB_HEADERS).filter(isOpenJob_).sort((a,b)=>new Date(b.approved_at||b.created_at)-new Date(a.approved_at||a.created_at)).map(jobPublic_);}
function jobDetailPublic_(id){expireJobs_();const j=findJob_(clean_(id,40));if(!j||!isOpenJob_(j))throw new Error('채용정보를 찾을 수 없습니다.');return jobPublic_(j);}
function alumniJobsPublic_(id){const aid=clean_(id,40);return listJobsPublic_().filter(j=>j.alumni_id===aid);}
function verifyJobAlumni_(b){const id=clean_(b.alumni_id,40),a=findAlumni_(id);if(!a||a.status!=='APPROVED'||!verifyPin_(id,b.edit_pin,a.edit_pin_hash))throw new Error('승인된 Alumni ID 또는 PIN이 올바르지 않습니다.');return{success:true,data:{alumni_id:id,name:maskName_(a.name),graduation_year:String(a.graduation_year||'')}};}
function validateJob_(b){required_(b,['company','job_title','recruit_type','employment_type','job_url']);enum_(b,'recruit_type');enum_(b,'employment_type');if(!url_(b.job_url))throw new Error('채용공고 URL 형식을 확인해 주세요.');if(!bool_(b.always_open)){if(!dateOnly_(b.deadline))throw new Error('마감일을 입력하거나 상시채용을 선택해 주세요.');if(dateOnly_(b.deadline)<Utilities.formatDate(new Date(),'Asia/Seoul','yyyy-MM-dd'))throw new Error('마감일이 지난 채용정보는 등록할 수 없습니다.');}if(String(b.alumni_comment||'').length>800)throw new Error('선배의 한마디는 800자 이내로 입력해 주세요.');}
function jobObject_(b){return{company:clean_(b.company,100),job_title:clean_(b.job_title,100),recruit_type:clean_(b.recruit_type,20),employment_type:clean_(b.employment_type,20),location:clean_(b.location,100),job_url:url_(b.job_url),deadline:bool_(b.always_open)?'':dateOnly_(b.deadline),always_open:bool_(b.always_open),skills:list_(b.skills,300),alumni_comment:clean_(b.alumni_comment,800),referral_available:bool_(b.referral_available),contact_allowed:bool_(b.contact_allowed)};}
function submitJob_(b){validateJob_(b);const aid=clean_(b.alumni_id,40),a=findAlumni_(aid);if(!a||a.status!=='APPROVED'||!verifyPin_(aid,b.edit_pin,a.edit_pin_hash))throw new Error('승인된 Alumni ID 또는 PIN이 올바르지 않습니다.');const lock=LockService.getScriptLock();lock.waitLock(10000);let job,nonce;try{const now=now_(),jid=id_('J');nonce=Utilities.getUuid()+Utilities.getUuid();job=Object.assign(jobObject_(b),{job_id:jid,alumni_id:aid,status:'PENDING',approved_at:'',approved_by:'',created_at:now,updated_at:now,last_mailed_at:'',approval_nonce_hash:digest_(nonce),approval_token_expires_at:Date.now()+7*24*60*60*1000});append_(SHEETS.JOBS,JOB_HEADERS,job);log_('submitJob','SUCCESS',jid,'PENDING');}finally{lock.releaseLock();}try{sendJobApprovalMail_(job,a,nonce);}catch(e){log_('jobApprovalMail','FAILED',job.job_id,e.message);}return{success:true,message:'채용정보 등록 신청이 완료되었습니다. 관리자 승인 후 공개됩니다.',job_id:job.job_id};}
function digest_(v){return Utilities.base64EncodeWebSafe(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(v))).replace(/=+$/,'');}
function jobApprovalToken_(jobId,decision,expires,nonce){const payload=[jobId,decision,expires,nonce].join('|'),sig=Utilities.base64EncodeWebSafe(Utilities.computeHmacSha256Signature(payload,approvalSecret_())).replace(/=+$/,'');return Utilities.base64EncodeWebSafe(payload).replace(/=+$/,'')+'.'+sig;}
function verifyJobApprovalToken_(token){const parts=String(token||'').split('.');if(parts.length!==2)throw new Error('승인 링크가 올바르지 않습니다.');let payload;try{payload=Utilities.newBlob(Utilities.base64DecodeWebSafe(parts[0])).getDataAsString();}catch(_){throw new Error('승인 링크가 올바르지 않습니다.');}const expected=Utilities.base64EncodeWebSafe(Utilities.computeHmacSha256Signature(payload,approvalSecret_())).replace(/=+$/,'');if(parts[1]!==expected)throw new Error('승인 링크가 올바르지 않습니다.');const values=payload.split('|');if(values.length!==4||!['APPROVED','REJECTED'].includes(values[1])||Date.now()>Number(values[2]))throw new Error('승인 링크가 만료되었거나 올바르지 않습니다.');return{jobId:values[0],decision:values[1],expires:Number(values[2]),nonce:values[3]};}
function siteUrl_(){return String(PropertiesService.getScriptProperties().getProperty('SITE_URL')||'https://alumni.k-bigdata.kr').replace(/\/$/,'');}
function sendJobApprovalMail_(j,a,nonce){const to=PropertiesService.getScriptProperties().getProperty('ADMIN_NOTIFICATION_EMAIL');if(!to||!email_(to))throw new Error('ADMIN_NOTIFICATION_EMAIL 설정이 필요합니다.');const base=ScriptApp.getService().getUrl()+'?action=moderateJob&token=',approve=base+encodeURIComponent(jobApprovalToken_(j.job_id,'APPROVED',j.approval_token_expires_at,nonce)),reject=base+encodeURIComponent(jobApprovalToken_(j.job_id,'REJECTED',j.approval_token_expires_at,nonce)),e=html_;MailApp.sendEmail({to,subject:'[BigData Alumni] 신규 채용정보 승인 요청 - '+j.company+' / '+j.job_title,name:'BigData Alumni Network',htmlBody:`<div style="font-family:Arial,sans-serif;max-width:640px;margin:auto;color:#243b53"><div style="background:#0b4f7a;color:#fff;padding:24px;border-radius:14px 14px 0 0"><b>BigData Alumni Network</b><h2 style="margin:8px 0 0">신규 채용정보 승인 요청</h2></div><div style="border:1px solid #d9e2ec;padding:22px;border-radius:0 0 14px 14px"><table style="width:100%;border-collapse:collapse">${[['회사',j.company],['직무',j.job_title],['채용구분',j.recruit_type],['고용형태',j.employment_type],['근무지역',j.location||'-'],['마감일',j.always_open?'상시채용':j.deadline],['주요 기술',j.skills||'-'],['등록 졸업생',a.name+' · '+a.graduation_year+'년'],['사내추천',j.referral_available?'가능':'일반 채용정보'],['선배의 한마디',j.alumni_comment||'-']].map(x=>`<tr><th style="text-align:left;vertical-align:top;padding:10px;background:#f3f7fa">${e(x[0])}</th><td style="padding:10px">${e(x[1])}</td></tr>`).join('')}</table><p><a href="${e(j.job_url)}" target="_blank">공식 채용공고 열기</a></p><div style="margin-top:24px"><a href="${e(approve)}" style="display:inline-block;background:#1477b8;color:#fff;text-decoration:none;font-weight:bold;padding:15px 24px;border-radius:9px;margin:0 8px 8px 0">채용정보 승인</a><a href="${e(reject)}" style="display:inline-block;background:#c0392b;color:#fff;text-decoration:none;font-weight:bold;padding:15px 24px;border-radius:9px">반려</a></div><p style="font-size:12px;color:#627d98">서명된 링크는 7일간 유효하며 한 번만 처리할 수 있습니다.</p></div></div>`});log_('jobApprovalMail','SUCCESS',j.job_id,to);}
function moderateJob_(jobId,status,approvedBy,nonce){const j=findJob_(jobId);if(!j)throw new Error('채용정보를 찾을 수 없습니다.');if(nonce&&j.status!=='PENDING')return{changed:false,job:j};if(nonce&&digest_(nonce)!==String(j.approval_nonce_hash))throw new Error('이미 사용했거나 올바르지 않은 승인 링크입니다.');const now=now_();j.status=status;j.updated_at=now;j.approval_nonce_hash='';j.approval_token_expires_at='';if(status==='APPROVED'){j.approved_at=now;j.approved_by=approvedBy;}const row=j.__row;delete j.__row;updateRow_(SHEETS.JOBS,JOB_HEADERS,row,j);log_('moderateJob','SUCCESS',jobId,status+'|'+approvedBy);return{changed:true,job:j};}
function moderateJobByEmail_(token){const t=verifyJobApprovalToken_(token),j=findJob_(t.jobId);if(!j)throw new Error('채용정보를 찾을 수 없습니다.');if(j.status!=='PENDING')return approvalPage_('이미 처리되었습니다',j.company+' · '+j.job_title+' 공고는 '+j.status+' 상태입니다.',true,siteUrl_()+'/job-detail.html?id='+encodeURIComponent(j.job_id));if(String(j.approval_token_expires_at)!==String(t.expires))throw new Error('승인 링크가 만료되었거나 올바르지 않습니다.');const r=moderateJob_(t.jobId,t.decision,'EMAIL_LINK',t.nonce),ok=t.decision==='APPROVED';return approvalPage_(ok?'채용정보가 승인되었습니다.':'채용정보가 반려되었습니다.',r.job.company+' · '+r.job.job_title, true,ok?siteUrl_()+'/job-detail.html?id='+encodeURIComponent(r.job.job_id):siteUrl_()+'/admin.html');}
function expireJobs_(){const today=Utilities.formatDate(new Date(),'Asia/Seoul','yyyy-MM-dd');rows_(SHEETS.JOBS,JOB_HEADERS).forEach(j=>{const deadline=dateOnly_(j.deadline);if(j.status==='APPROVED'&&!bool_(j.always_open)&&deadline&&deadline<today){j.status='EXPIRED';j.updated_at=now_();const row=j.__row;delete j.__row;updateRow_(SHEETS.JOBS,JOB_HEADERS,row,j);}});}

function adminList_(b){const email=verifyAdmin_(b.admin_token),views=['alumni','jobs','news','requests','mail_logs'],view=views.includes(b.view)?b.view:'alumni';log_('adminList','SUCCESS',email,view);if(view==='requests')return{success:true,data:rows_(SHEETS.CONTACTS,CONTACT_HEADERS).map(x=>{delete x.__row;delete x.requester_email;delete x.requester_phone;delete x.message;return x;})};if(view==='mail_logs'){const jobs=rows_(SHEETS.JOB_MAIL_LOGS,JOB_MAIL_LOG_HEADERS).map(x=>({mail_kind:'채용정보',related_id:x.job_ids,subject:'채용정보 Digest',recipient_count:x.recipient_count,sent_count:x.sent_count,failed_count:x.failed_count,sent_at:normalizeOut_('',x.sent_at),status:x.status})),news=rows_(SHEETS.NEWS_MAIL_LOGS,NEWS_MAIL_LOG_HEADERS).map(x=>({mail_kind:'동문소식',related_id:x.news_id,subject:x.subject,recipient_count:x.recipient_count,sent_count:x.sent_count,failed_count:x.failed_count,sent_at:normalizeOut_('',x.sent_at),status:x.status}));return{success:true,data:jobs.concat(news).sort((a,b)=>String(b.sent_at).localeCompare(String(a.sent_at)))};}if(view==='jobs'){expireJobs_();return{success:true,data:rows_(SHEETS.JOBS,JOB_HEADERS).map(x=>{const a=findAlumni_(x.alumni_id)||{},safe=jobPublic_(x);safe.status=x.status;safe.approved_at=normalizeOut_('',x.approved_at);safe.created_at=normalizeOut_('',x.created_at);safe.alumni_name_admin=String(a.name||'');delete safe.job_url;return safe;})};}if(view==='news')return{success:true,data:rows_(SHEETS.NEWS,NEWS_HEADERS).map(n=>{const target=findAlumni_(n.alumni_id)||{},submitter=findAlumni_(n.submitted_by_alumni_id)||{},safe=newsPublic_(n);safe.target_name_admin=String(target.name||'');safe.submitter_name_admin=String(submitter.name||n.submitted_by_alumni_id||'');safe.status=n.status;safe.mail_requested=bool_(n.mail_requested);safe.mail_status=String(n.mail_status||'');safe.created_at=normalizeOut_('',n.created_at);return safe;})};return{success:true,data:rows_(SHEETS.ALUMNI,ALUMNI_HEADERS).map(x=>{const safe=public_(x);safe.email=String(x.email||'');safe.phone=String(x.phone||'');safe.status=x.status;safe.created_at=normalizeOut_('',x.created_at);safe.career_mail_enabled=normalizeOut_('career_mail_enabled',x.career_mail_enabled);safe.alumni_news_mail_enabled=normalizeOut_('alumni_news_mail_enabled',x.alumni_news_mail_enabled);return safe;})};}
function adminStatus_(action,b){const email=verifyAdmin_(b.admin_token),map={adminApprove:'APPROVED',adminReject:'REJECTED',adminHide:'HIDDEN'},x=findAlumni_(clean_(b.alumni_id,40));if(!x)throw new Error('졸업생 정보를 찾을 수 없습니다.');x.status=map[action];x.updated_at=now_();const row=x.__row;delete x.__row;updateRow_(SHEETS.ALUMNI,ALUMNI_HEADERS,row,x);log_(action,'SUCCESS',x.alumni_id,email);return{success:true,message:'상태가 변경되었습니다.'};}
function adminJobStatus_(action,b){const email=verifyAdmin_(b.admin_token),map={adminJobApprove:'APPROVED',adminJobReject:'REJECTED',adminJobHide:'HIDDEN',adminJobPublish:'APPROVED'};moderateJob_(clean_(b.job_id,40),map[action],email,'');return{success:true,message:'채용정보 상태가 변경되었습니다.'};}
function adminSendCareerConsentInvites_(b){const admin=verifyAdmin_(b.admin_token),sentIds=new Set(rows_(SHEETS.CONSENT_INVITES,CONSENT_INVITE_HEADERS).filter(x=>x.status==='SENT').map(x=>String(x.alumni_id))),targets=rows_(SHEETS.ALUMNI,ALUMNI_HEADERS).filter(x=>x.status==='APPROVED'&&String(x.career_mail_enabled)===''&&email_(x.email)&&!sentIds.has(String(x.alumni_id)));let sent=0,failed=0;targets.forEach(a=>{try{MailApp.sendEmail({to:String(a.email),subject:'[BigData Alumni] 채용정보 이메일 수신 설정 안내',name:'BigData Alumni Network',htmlBody:consentInviteHtml_(a)});append_(SHEETS.CONSENT_INVITES,CONSENT_INVITE_HEADERS,{invite_id:id_('I'),alumni_id:a.alumni_id,sent_at:now_(),status:'SENT'});sent++;}catch(e){failed++;log_('careerConsentInvite','FAILED',a.alumni_id,e.message);}});log_('careerConsentInvites','SUCCESS','',admin+'|sent='+sent+'|failed='+failed);return{success:true,message:'수신 설정 안내 메일 처리 완료: 성공 '+sent+'명, 실패 '+failed+'명'};}
function consentInviteHtml_(a){const e=html_,url=siteUrl_()+'/alumni.html';return `<div style="font-family:Arial,sans-serif;max-width:620px;margin:auto;color:#243b53"><div style="background:#0b4f7a;color:#fff;padding:24px;border-radius:14px 14px 0 0"><b>BigData Alumni Network</b><h2 style="margin:8px 0 0">채용정보 이메일 수신 설정 안내</h2></div><div style="border:1px solid #d9e2ec;padding:24px;border-radius:0 0 14px 14px"><p>${e(a.name)} 졸업생님, 선배들이 공유한 채용·추천 정보를 확인할 수 있는 채용정보 기능이 추가되었습니다.</p><p>수신을 원하시면 아래 버튼을 눌러 Alumni ID와 수정 PIN으로 본인 정보를 불러온 뒤 ‘취업·채용정보 이메일 수신’에 동의해 주세요.</p><p><a href="${e(url)}" style="display:inline-block;background:#1477b8;color:#fff;text-decoration:none;font-weight:bold;padding:15px 22px;border-radius:9px">채용정보 이메일 수신 설정</a></p><p style="font-size:13px;color:#627d98">수신을 원하지 않으면 아무 조치도 하지 않아도 되며, 채용정보 메일은 발송되지 않습니다.</p></div></div>`;}
function adminRunJobDigest_(b){const email=verifyAdmin_(b.admin_token),r=sendDailyJobDigest();log_('adminRunJobDigest','SUCCESS','',email);return{success:true,message:r.message||'채용정보 메일 발송 작업이 완료되었습니다.',data:r};}
function sendDailyJobDigest(){expireJobs_();const jobs=rows_(SHEETS.JOBS,JOB_HEADERS).filter(j=>isOpenJob_(j)&&!j.last_mailed_at);if(!jobs.length)return{status:'NO_JOBS',message:'새로 발송할 채용정보가 없습니다.'};const recipients=rows_(SHEETS.ALUMNI,ALUMNI_HEADERS).filter(a=>a.status==='APPROVED'&&String(a.career_mail_enabled).toLowerCase()==='true'&&email_(a.email));const mailId=id_('M'),ids=jobs.map(j=>j.job_id).join('|'),stamp=now_();if(!recipients.length){markJobsMailed_(jobs,stamp);append_(SHEETS.JOB_MAIL_LOGS,JOB_MAIL_LOG_HEADERS,{mail_id:mailId,job_ids:ids,recipient_count:0,sent_count:0,failed_count:0,sent_at:stamp,status:'NO_RECIPIENTS'});return{status:'NO_RECIPIENTS',message:'수신 동의한 졸업생이 없어 발송하지 않았습니다.'};}const quota=MailApp.getRemainingDailyQuota();if(quota<recipients.length){append_(SHEETS.JOB_MAIL_LOGS,JOB_MAIL_LOG_HEADERS,{mail_id:mailId,job_ids:ids,recipient_count:recipients.length,sent_count:0,failed_count:0,sent_at:stamp,status:'QUOTA_BLOCKED'});return{status:'QUOTA_BLOCKED',message:'메일 일일 한도가 부족해 발송을 보류했습니다.'};}const html=jobDigestHtml_(jobs),subject='[BigData Alumni] 오늘의 신규 채용정보 '+jobs.length+'건';let sent=0,failed=0;recipients.forEach(a=>{try{MailApp.sendEmail({to:String(a.email),subject,name:'BigData Alumni Network',htmlBody:html});sent++;}catch(e){failed++;log_('jobDigestRecipient','FAILED',a.alumni_id,e.message);}});markJobsMailed_(jobs,stamp);const status=failed===0?'SENT':sent?'PARTIAL':'FAILED';append_(SHEETS.JOB_MAIL_LOGS,JOB_MAIL_LOG_HEADERS,{mail_id:mailId,job_ids:ids,recipient_count:recipients.length,sent_count:sent,failed_count:failed,sent_at:stamp,status});return{status,sent,failed,message:'채용정보 메일: 성공 '+sent+'명, 실패 '+failed+'명'};}
function markJobsMailed_(jobs,stamp){jobs.forEach(j=>{j.last_mailed_at=stamp;j.updated_at=stamp;const row=j.__row;delete j.__row;updateRow_(SHEETS.JOBS,JOB_HEADERS,row,j);});}
function jobDigestHtml_(jobs){const e=html_,base=siteUrl_();return `<div style="font-family:Arial,sans-serif;max-width:640px;margin:auto;color:#243b53"><div style="background:#0b4f7a;color:#fff;padding:24px;border-radius:14px 14px 0 0"><b>BigData Alumni Network</b><h2 style="margin:8px 0 0">오늘의 채용정보</h2><p style="margin-bottom:0">선배들이 공유한 새로운 채용정보를 확인하세요.</p></div><div style="padding:18px;background:#f3f7fa">${jobs.map(j=>{const a=findAlumni_(j.alumni_id)||{},url=base+'/job-detail.html?id='+encodeURIComponent(j.job_id);return `<div style="background:#fff;border:1px solid #d9e2ec;border-radius:12px;padding:20px;margin-bottom:14px"><div style="font-size:13px;color:#486581">${e(j.recruit_type)} · ${e(j.employment_type)} · ${e(j.location||'근무지역 협의')}</div><h3 style="margin:8px 0 4px;color:#102a43">${e(j.company)}</h3><p style="font-size:17px;font-weight:bold;margin:0 0 12px">${e(j.job_title)}</p><p style="margin:6px 0">${j.always_open?'상시채용':'마감 '+e(dateOnly_(j.deadline))}</p><p style="margin:6px 0;color:#486581">${e(String(j.skills||'').split('|').join(' · ')||'기술 정보 없음')}</p><p style="margin:6px 0">${e(a.graduation_year)}년 졸업생 공유${bool_(j.referral_available)?' · <b style="color:#1477b8">사내추천 가능</b>':''}</p><a href="${e(url)}" style="display:inline-block;margin-top:10px;background:#1477b8;color:#fff;text-decoration:none;font-weight:bold;padding:12px 18px;border-radius:8px">채용정보 자세히 보기</a></div>`;}).join('')}<div style="text-align:center;padding:10px"><a href="${e(base+'/jobs.html')}" style="display:inline-block;border:1px solid #1477b8;color:#1477b8;text-decoration:none;font-weight:bold;padding:13px 20px;border-radius:8px">전체 채용정보 보기</a></div></div></div>`;}
function installDailyJobDigestTrigger(){const exists=ScriptApp.getProjectTriggers().some(t=>t.getHandlerFunction()==='sendDailyJobDigest');if(!exists)ScriptApp.newTrigger('sendDailyJobDigest').timeBased().atHour(8).everyDays(1).inTimezone('Asia/Seoul').create();return exists?'기존 트리거가 이미 있습니다.':'매일 오전 8시 채용정보 메일 트리거를 생성했습니다.';}
function verifyAdmin_(token){if(!token)throw new Error('관리자 권한이 필요합니다.');const client=PropertiesService.getScriptProperties().getProperty('GOOGLE_CLIENT_ID');if(!client)throw new Error('관리자 인증 설정이 필요합니다.');let info;try{const res=UrlFetchApp.fetch('https://oauth2.googleapis.com/tokeninfo?id_token='+encodeURIComponent(token),{muteHttpExceptions:true});info=JSON.parse(res.getContentText());}catch(e){throw new Error('관리자 인증에 실패했습니다.');}if(info.aud!==client||!['accounts.google.com','https://accounts.google.com'].includes(info.iss)||info.email_verified!=='true')throw new Error('관리자 권한이 없습니다.');const ok=rows_(SHEETS.ADMINS,ADMIN_HEADERS).some(x=>String(x.email).toLowerCase()===String(info.email).toLowerCase()&&x.status==='ACTIVE');if(!ok)throw new Error('관리자 권한이 없습니다.');return info.email;}

function approvalSecret_(){const props=PropertiesService.getScriptProperties();let secret=props.getProperty('APPROVAL_TOKEN_SECRET');if(!secret){const lock=LockService.getScriptLock();lock.waitLock(10000);try{secret=props.getProperty('APPROVAL_TOKEN_SECRET');if(!secret){secret=Utilities.getUuid()+Utilities.getUuid();props.setProperty('APPROVAL_TOKEN_SECRET',secret);}}finally{lock.releaseLock();}}return secret;}
function approvalToken_(id){const payload=id+'|'+(Date.now()+7*24*60*60*1000),sig=Utilities.base64EncodeWebSafe(Utilities.computeHmacSha256Signature(payload,approvalSecret_())).replace(/=+$/,'');return Utilities.base64EncodeWebSafe(payload).replace(/=+$/,'')+'.'+sig;}
function verifyApprovalToken_(token){const parts=String(token||'').split('.');if(parts.length!==2)throw new Error('승인 링크가 올바르지 않습니다.');let payload;try{payload=Utilities.newBlob(Utilities.base64DecodeWebSafe(parts[0])).getDataAsString();}catch(_){throw new Error('승인 링크가 올바르지 않습니다.');}const expected=Utilities.base64EncodeWebSafe(Utilities.computeHmacSha256Signature(payload,approvalSecret_())).replace(/=+$/,'');if(parts[1]!==expected)throw new Error('승인 링크가 올바르지 않습니다.');const split=payload.lastIndexOf('|'),id=payload.slice(0,split),expires=Number(payload.slice(split+1));if(!id||!expires||Date.now()>expires)throw new Error('승인 링크가 만료되었습니다. 관리자 화면에서 승인해 주세요.');return id;}
function sendApprovalMail_(a){const to=PropertiesService.getScriptProperties().getProperty('ADMIN_NOTIFICATION_EMAIL');if(!to||!email_(to))throw new Error('ADMIN_NOTIFICATION_EMAIL 설정이 필요합니다.');const url=ScriptApp.getService().getUrl()+'?action=approveByEmail&token='+encodeURIComponent(approvalToken_(a.alumni_id)),e=html_;MailApp.sendEmail({to,subject:'[BigData Alumni] '+a.name+' 졸업생 등록 승인 요청',name:'BigData Alumni Network',htmlBody:`<div style="font-family:Arial,sans-serif;max-width:640px;margin:auto;color:#243b53"><div style="background:#0b4f7a;color:white;padding:24px;border-radius:14px 14px 0 0"><h2 style="margin:0">졸업생 등록 승인 요청</h2></div><div style="border:1px solid #d9e2ec;padding:24px;border-radius:0 0 14px 14px"><p><b>${e(a.name)}</b> 졸업생이 새 정보를 등록했습니다.</p><table style="width:100%;border-collapse:collapse"><tr><th style="text-align:left;padding:8px;background:#f3f7fa">졸업연도</th><td style="padding:8px">${e(a.graduation_year)}</td></tr><tr><th style="text-align:left;padding:8px;background:#f3f7fa">현재 상태</th><td style="padding:8px">${e(a.employment_status)}</td></tr><tr><th style="text-align:left;padding:8px;background:#f3f7fa">회사/직무</th><td style="padding:8px">${e([a.company,a.job].filter(Boolean).join(' · ')||'-')}</td></tr><tr><th style="text-align:left;padding:8px;background:#f3f7fa">대학원 상태</th><td style="padding:8px">${e(a.graduate_status||'-')}</td></tr></table><p style="margin:24px 0"><a href="${e(url)}" style="display:inline-block;background:#1477b8;color:white;text-decoration:none;font-weight:bold;padding:14px 24px;border-radius:9px">이 졸업생 승인하기</a></p><p style="font-size:12px;color:#627d98">승인 링크는 7일 동안 유효합니다. 이메일·휴대전화·PIN은 이 메일에 포함되지 않습니다.</p></div></div>`});log_('approvalMail','SUCCESS',a.alumni_id,to);}
function approveByEmail_(token){const id=verifyApprovalToken_(token),x=findAlumni_(id);if(!x)throw new Error('졸업생 정보를 찾을 수 없습니다.');if(x.status==='APPROVED')return approvalPage_('이미 승인되었습니다',x.name+' 졸업생은 이미 공개 상태입니다.',true);if(x.status!=='PENDING')throw new Error('승인 대기 상태가 아닙니다. 관리자 화면에서 확인해 주세요.');x.status='APPROVED';x.updated_at=now_();const row=x.__row;delete x.__row;updateRow_(SHEETS.ALUMNI,ALUMNI_HEADERS,row,x);log_('approveByEmail','SUCCESS',id,'signed-email-link');return approvalPage_('승인 완료',x.name+' 졸업생 정보가 공개되었습니다.',true);}
function approvalPage_(title,message,ok,url){const href=url||siteUrl_()+'/admin.html',label=url&&url.includes('job-detail')?'채용정보 확인':'관리자 화면 열기';return HtmlService.createHtmlOutput(`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${html_(title)}</title></head><body style="margin:0;background:#f3f7fa;font-family:Arial,sans-serif;color:#243b53"><main style="max-width:560px;margin:12vh auto;padding:24px"><section style="background:white;border-radius:16px;padding:32px;box-shadow:0 8px 30px rgba(16,42,67,.12);text-align:center"><div style="font-size:42px">${ok?'✓':'!'}</div><h1>${html_(title)}</h1><p>${html_(message)}</p><a href="${html_(href)}" style="display:inline-block;margin-top:16px;background:#1477b8;color:#fff;text-decoration:none;font-weight:bold;padding:13px 20px;border-radius:8px">${html_(label)}</a></section></main></body></html>`).setTitle(title);}

function hashPin_(id,pin){const pepper=PropertiesService.getScriptProperties().getProperty('PIN_PEPPER');if(!pepper)throw new Error('PIN 보안 설정이 필요합니다. setup을 실행해 주세요.');return Utilities.base64EncodeWebSafe(Utilities.computeHmacSha256Signature(id+'|'+pin,pepper));}
function verifyPin_(id,pin,hash){return /^\d{6,12}$/.test(String(pin||''))&&hashPin_(id,pin)===String(hash);}
function log_(action,result,ref,detail){try{append_(SHEETS.LOGS,LOG_HEADERS,{log_id:id_('L'),action,result,reference_id:ref,detail:clean_(detail,500),created_at:now_()});}catch(_){}}
function required_(b,ks){ks.forEach(k=>{if(b[k]===undefined||b[k]===null||String(b[k]).trim()==='')throw new Error(k+' 필수 입력값을 확인해 주세요.');});}
function enum_(b,k){if(!ENUMS[k].includes(String(b[k])))throw new Error(k+' 입력값이 올바르지 않습니다.');}
function clean_(v,max){let s=String(v===undefined||v===null?'':v).replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,'').trim().slice(0,max||500);return /^[=+@]|^-[^0-9]/.test(s)?"'"+s:s;}
function list_(v,max){const a=Array.isArray(v)?v:String(v||'').split(/[|,]/);return a.map(x=>clean_(x,60)).filter(Boolean).slice(0,20).join('|').slice(0,max||300);}
function bool_(v){return v===true||String(v).toLowerCase()==='true';}
function phoneText_(v){const s=clean_(v,20);return /^\d{9,10}$/.test(s)&&s.charAt(0)!=='0'?'0'+s:s;}
function email_(v){return /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(String(v||''))&&String(v).length<=120;}
function phone_(v){return /^[0-9+()\-\s]{8,20}$/.test(String(v||''));}
function limit_(k){return ({name:40,email:120,phone:20,company_url:300,job_description:500,introduction:500,message_to_juniors:500}[k]||100);}
function html_(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}

function repairPhoneLeadingZeros(){[[SHEETS.ALUMNI,ALUMNI_HEADERS,'phone'],[SHEETS.CONTACTS,CONTACT_HEADERS,'requester_phone']].forEach(([name,headers,key])=>{const sh=sheet_(name),col=headers.indexOf(key)+1,last=sh.getLastRow();if(last<2||col<1)return;const range=sh.getRange(2,col,last-1,1),values=range.getDisplayValues().map(([v])=>[phoneText_(v)]);range.setNumberFormat('@');range.setValues(values);});}

function newsLabel_(type){return NEWS_LABELS[String(type)]||'기타';}
function findNews_(id){return rows_(SHEETS.NEWS,NEWS_HEADERS).find(x=>String(x.news_id)===String(id));}
function newsPublic_(n){const a=findAlumni_(n.alumni_id)||{};return{news_id:String(n.news_id||''),alumni_id:String(n.alumni_id||''),name:maskName_(a.name),graduation_year:String(a.graduation_year||''),news_type:String(n.news_type||''),news_type_label:newsLabel_(n.news_type),title:String(n.title||''),content:String(n.content||''),company:String(n.company||''),job_title:String(n.job_title||''),organization:String(n.organization||''),position_title:String(n.position_title||''),school_name:String(n.school_name||''),degree_or_program:String(n.degree_or_program||''),event_date:dateOnly_(n.event_date),location:String(n.location||''),relationship:String(n.relationship||''),external_url:String(n.external_url||''),created_at:normalizeOut_('',n.created_at)};}
function listNewsPublic_(){return rows_(SHEETS.NEWS,NEWS_HEADERS).filter(n=>n.status==='APPROVED').sort((a,b)=>String(b.event_date||b.created_at).localeCompare(String(a.event_date||a.created_at))).map(newsPublic_);}
function newsDetailPublic_(id){const n=findNews_(clean_(id,40));if(!n||n.status!=='APPROVED')throw new Error('동문소식을 찾을 수 없습니다.');return newsPublic_(n);}
function alumniNewsPublic_(id){const aid=clean_(id,40);return listNewsPublic_().filter(n=>n.alumni_id===aid);}
function verifyNewsAlumni_(b){const id=clean_(b.alumni_id,40),a=findAlumni_(id);if(!a||a.status!=='APPROVED'||!verifyPin_(id,b.edit_pin,a.edit_pin_hash))throw new Error('승인된 Alumni ID 또는 PIN이 올바르지 않습니다.');return{success:true,data:{alumni_id:id,name:maskName_(a.name),graduation_year:String(a.graduation_year||'')}};}
function newsAlumniSearch_(b){verifyNewsAlumni_(b);const q=clean_(b.query,60).toLowerCase();if(q.length<1)throw new Error('검색어를 입력해 주세요.');return{success:true,data:rows_(SHEETS.ALUMNI,ALUMNI_HEADERS).filter(a=>a.status==='APPROVED'&&[a.name,a.company,a.job,a.graduation_year].join(' ').toLowerCase().includes(q)).slice(0,20).map(a=>({alumni_id:a.alumni_id,name:maskName_(a.name),graduation_year:String(a.graduation_year||''),company:String(a.company||''),job:String(a.job||'')}))};}
function validateNews_(b){if(!NEWS_TYPES.includes(String(b.news_type)))throw new Error('동문소식 종류가 올바르지 않습니다.');required_(b,['title','content']);if(String(b.title).trim().length>120||String(b.content).trim().length>2000)throw new Error('제목 또는 내용 길이를 확인해 주세요.');if(b.external_url&&!url_(b.external_url))throw new Error('외부 URL 형식을 확인해 주세요.');if(b.event_date&&!/^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2})?$/.test(String(b.event_date)))throw new Error('관련 날짜 형식을 확인해 주세요.');if(b.news_type==='OBITUARY'){required_(b,['target_alumni_id','relationship']);}const allowedRel=['본인','부친','모친','배우자','자녀','조부','조모','장인','장모','기타'];if(b.news_type==='OBITUARY'&&!allowedRel.includes(String(b.relationship)))throw new Error('고인과의 관계를 확인해 주세요.');}
function newsObject_(b){return{news_type:String(b.news_type),title:clean_(b.title,120),content:clean_(b.content,2000),company:clean_(b.company,100),job_title:clean_(b.job_title,100),organization:clean_(b.organization,120),position_title:clean_(b.position_title,100),school_name:clean_(b.school_name,120),degree_or_program:clean_(b.degree_or_program,120),event_date:clean_(b.event_date,30),location:clean_(b.location,200),relationship:clean_(b.relationship==='기타'&&b.relationship_other?b.relationship_other:b.relationship,60),external_url:clean_(b.external_url,500),mail_requested:bool_(b.mail_requested)};}
function submitNews_(b){validateNews_(b);const submitterId=clean_(b.alumni_id,40),submitter=findAlumni_(submitterId);if(!submitter||submitter.status!=='APPROVED'||!verifyPin_(submitterId,b.edit_pin,submitter.edit_pin_hash))throw new Error('승인된 Alumni ID 또는 PIN이 올바르지 않습니다.');const targetId=b.news_type==='OBITUARY'?clean_(b.target_alumni_id,40):submitterId,target=findAlumni_(targetId);if(!target||target.status!=='APPROVED')throw new Error('소식 대상 졸업생을 찾을 수 없습니다.');const lock=LockService.getScriptLock();lock.waitLock(10000);let news,nonce;try{const now=now_(),nid=id_('N');nonce=Utilities.getUuid()+Utilities.getUuid();news=Object.assign(newsObject_(b),{news_id:nid,alumni_id:targetId,submitted_by_alumni_id:submitterId,mail_status:bool_(b.mail_requested)?'WAITING':'NOT_REQUESTED',status:'PENDING',approved_at:'',approved_by:'',created_at:now,updated_at:now,approval_nonce_hash:digest_(nonce),approval_token_expires_at:Date.now()+7*24*60*60*1000});append_(SHEETS.NEWS,NEWS_HEADERS,news);log_('submitNews','SUCCESS',nid,'PENDING');}finally{lock.releaseLock();}try{sendNewsApprovalMail_(news,target,submitter,nonce);}catch(e){log_('newsApprovalMail','FAILED',news.news_id,e.message);}return{success:true,message:'동문소식 등록 신청이 완료되었습니다. 관리자 승인 후 공개됩니다.',news_id:news.news_id};}
function newsApprovalToken_(newsId,decision,expires,nonce){const payload=['NEWS',newsId,decision,expires,nonce].join('|'),sig=Utilities.base64EncodeWebSafe(Utilities.computeHmacSha256Signature(payload,approvalSecret_())).replace(/=+$/,'');return Utilities.base64EncodeWebSafe(payload).replace(/=+$/,'')+'.'+sig;}
function verifyNewsApprovalToken_(token){const parts=String(token||'').split('.');if(parts.length!==2)throw new Error('승인 링크가 올바르지 않습니다.');let payload;try{payload=Utilities.newBlob(Utilities.base64DecodeWebSafe(parts[0])).getDataAsString();}catch(_){throw new Error('승인 링크가 올바르지 않습니다.');}const expected=Utilities.base64EncodeWebSafe(Utilities.computeHmacSha256Signature(payload,approvalSecret_())).replace(/=+$/,'');if(parts[1]!==expected)throw new Error('승인 링크가 올바르지 않습니다.');const p=payload.split('|');if(p.length!==5||p[0]!=='NEWS'||!['APPROVE_MAIL','APPROVE_ONLY','REJECTED'].includes(p[2])||Date.now()>Number(p[3]))throw new Error('승인 링크가 만료되었거나 올바르지 않습니다.');return{newsId:p[1],decision:p[2],expires:p[3],nonce:p[4]};}
function sendNewsApprovalMail_(n,target,submitter,nonce){const to=PropertiesService.getScriptProperties().getProperty('ADMIN_NOTIFICATION_EMAIL');if(!to||!email_(to))throw new Error('ADMIN_NOTIFICATION_EMAIL 설정이 필요합니다.');const base=ScriptApp.getService().getUrl()+'?action=moderateNews&token=',make=d=>base+encodeURIComponent(newsApprovalToken_(n.news_id,d,n.approval_token_expires_at,nonce)),e=html_,rows=[['소식 종류',newsLabel_(n.news_type)],['소식 대상',target.name+' · '+target.graduation_year+'년 졸업'],['등록자',submitter.name+' · '+submitter.graduation_year+'년 졸업'],['관계',n.relationship||'-'],['제목',n.title],['관련 날짜',n.event_date||'-'],['장소',n.location||'-'],['메일발송 요청',n.mail_requested?'예':'아니오']];MailApp.sendEmail({to,subject:'[BigData Alumni] 동문소식 승인 요청 - '+newsLabel_(n.news_type)+' / '+target.name,name:'BigData Alumni Network',htmlBody:`<div style="font-family:Arial,sans-serif;max-width:640px;margin:auto;color:#243b53"><div style="background:#0b4f7a;color:#fff;padding:24px;border-radius:14px 14px 0 0"><b>BigData Alumni Network</b><h2 style="margin:8px 0 0">동문소식 승인 요청</h2></div><div style="border:1px solid #d9e2ec;padding:22px;border-radius:0 0 14px 14px"><table style="width:100%;border-collapse:collapse">${rows.map(x=>`<tr><th style="text-align:left;vertical-align:top;padding:10px;background:#f3f7fa">${e(x[0])}</th><td style="padding:10px">${e(x[1])}</td></tr>`).join('')}</table><p>${e(n.content)}</p>${n.external_url?`<p><a href="${e(n.external_url)}">외부 안내 페이지 확인</a></p>`:''}<div style="margin-top:24px"><a href="${e(make('APPROVE_MAIL'))}" style="display:inline-block;background:#1477b8;color:#fff;text-decoration:none;font-weight:bold;padding:15px 18px;border-radius:9px;margin:0 6px 8px 0">게시 + 이메일 발송</a><a href="${e(make('APPROVE_ONLY'))}" style="display:inline-block;background:#157347;color:#fff;text-decoration:none;font-weight:bold;padding:15px 18px;border-radius:9px;margin:0 6px 8px 0">게시만 하기</a><a href="${e(make('REJECTED'))}" style="display:inline-block;background:#b42318;color:#fff;text-decoration:none;font-weight:bold;padding:15px 18px;border-radius:9px">반려</a></div><p style="font-size:12px;color:#627d98">서명된 링크는 7일간 유효하며 한 번만 처리할 수 있습니다.</p></div></div>`});}
function moderateNewsByEmail_(token){const t=verifyNewsApprovalToken_(token),n=findNews_(t.newsId);if(!n)throw new Error('동문소식을 찾을 수 없습니다.');if(n.status!=='PENDING')return approvalPage_('이미 처리되었습니다',n.title+' 소식은 '+n.status+' 상태입니다.',true,siteUrl_()+'/news-detail.html?id='+encodeURIComponent(n.news_id));if(String(n.approval_token_expires_at)!==String(t.expires)||digest_(t.nonce)!==String(n.approval_nonce_hash))throw new Error('이미 사용했거나 만료된 승인 링크입니다.');const result=moderateNews_(n,t.decision,'EMAIL_LINK',t.nonce);return approvalPage_(t.decision==='REJECTED'?'동문소식이 반려되었습니다.':'동문소식이 게시되었습니다.',result.news.title+(result.mailResult?' · '+result.mailResult.status:''),true,t.decision==='REJECTED'?siteUrl_()+'/admin.html':siteUrl_()+'/news-detail.html?id='+encodeURIComponent(n.news_id));}
function moderateNews_(n,decision,approvedBy,nonce){if(nonce&&n.status!=='PENDING')return{changed:false,news:n};if(nonce&&digest_(nonce)!==String(n.approval_nonce_hash))throw new Error('이미 사용했거나 올바르지 않은 승인 링크입니다.');const now=now_();n.status=decision==='REJECTED'?'REJECTED':'APPROVED';n.updated_at=now;n.approval_nonce_hash='';n.approval_token_expires_at='';if(n.status==='APPROVED'){n.approved_at=now;n.approved_by=approvedBy;}if(decision==='APPROVE_ONLY')n.mail_status='NOT_REQUESTED';const row=n.__row;delete n.__row;updateRow_(SHEETS.NEWS,NEWS_HEADERS,row,n);let mailResult=null;if(decision==='APPROVE_MAIL')mailResult=sendAlumniNewsMail_(n);log_('moderateNews','SUCCESS',n.news_id,decision+'|'+approvedBy);return{changed:true,news:n,mailResult};}
function sendAlumniNewsMail_(n){const existing=rows_(SHEETS.NEWS_MAIL_LOGS,NEWS_MAIL_LOG_HEADERS).find(x=>x.news_id===n.news_id&&x.status==='SENT');if(existing)return{status:'SENT',message:'이미 발송 완료된 동문소식입니다.'};const recipients=rows_(SHEETS.ALUMNI,ALUMNI_HEADERS).filter(a=>a.status==='APPROVED'&&String(a.alumni_news_mail_enabled).toLowerCase()==='true'&&email_(a.email)),a=findAlumni_(n.alumni_id)||{},subject=newsMailSubject_(n,a),stamp=now_(),mailId=id_('NM');if(!recipients.length){n.mail_status='NO_RECIPIENTS';updateNewsMailStatus_(n);appendNewsMailLog_(mailId,n,subject,0,0,0,stamp,'NO_RECIPIENTS');return{status:'NO_RECIPIENTS'};}if(MailApp.getRemainingDailyQuota()<recipients.length){n.mail_status='QUOTA_BLOCKED';updateNewsMailStatus_(n);appendNewsMailLog_(mailId,n,subject,recipients.length,0,0,stamp,'QUOTA_BLOCKED');return{status:'QUOTA_BLOCKED'};}const body=newsMailHtml_(n,a);let sent=0,failed=0;recipients.forEach(r=>{try{MailApp.sendEmail({to:String(r.email),subject,name:'BigData Alumni Network',htmlBody:body});sent++;}catch(e){failed++;log_('alumniNewsRecipient','FAILED',r.alumni_id,e.message);}});const status=failed===0?'SENT':sent?'PARTIAL_FAILED':'FAILED';n.mail_status=status;updateNewsMailStatus_(n);appendNewsMailLog_(mailId,n,subject,recipients.length,sent,failed,stamp,status);return{status,sent,failed};}
function updateNewsMailStatus_(n){const found=findNews_(n.news_id);if(!found)return;found.mail_status=n.mail_status;found.updated_at=now_();const row=found.__row;delete found.__row;updateRow_(SHEETS.NEWS,NEWS_HEADERS,row,found);}
function appendNewsMailLog_(id,n,subject,count,sent,failed,at,status){append_(SHEETS.NEWS_MAIL_LOGS,NEWS_MAIL_LOG_HEADERS,{mail_id:id,news_id:n.news_id,news_type:n.news_type,subject,recipient_count:count,sent_count:sent,failed_count:failed,sent_at:at,status});}
function newsMailSubject_(n,a){return '[BigData Alumni] '+String(a.name||'동문')+' 동문 '+newsLabel_(n.news_type)+' '+(n.news_type==='OBITUARY'?'안내':'소식');}
function newsMailHtml_(n,a){const obituary=n.news_type==='OBITUARY',accent=obituary?'#4b5563':'#0b4f7a',e=html_,profile=maskName_(a.name)+' · '+String(a.graduation_year||'')+'년 졸업',detail=siteUrl_()+'/news-detail.html?id='+encodeURIComponent(n.news_id),intro=obituary?'부고를 알려드립니다.':(['MARRIAGE','BIRTH_SON','BIRTH_DAUGHTER'].includes(n.news_type)?'동문의 기쁜 소식을 전합니다.':'주요 동문소식을 전합니다.');return`<div style="font-family:Arial,sans-serif;max-width:620px;margin:auto;color:#243b53"><div style="background:${accent};color:#fff;padding:24px"><b>BigData Alumni Network</b><h2 style="margin:8px 0 0">${e(intro)}</h2></div><div style="border:1px solid #d9e2ec;padding:24px"><p style="font-size:18px"><b>${e(profile)}</b></p><h2>${e(n.title)}</h2><p style="white-space:pre-line;line-height:1.7">${e(n.content)}</p>${n.event_date?`<p><b>${obituary?'발인/관련일':'일시'}</b><br>${e(n.event_date)}</p>`:''}${n.location?`<p><b>${obituary?'빈소/장소':'장소'}</b><br>${e(n.location)}</p>`:''}${obituary?'<p style="font-weight:bold">삼가 고인의 명복을 빕니다.</p>':''}${n.external_url?`<p><a href="${e(n.external_url)}" style="color:${accent}">${obituary?'부고 자세히 보기':'외부 안내 페이지 보기'}</a></p>`:''}<p><a href="${e(detail)}" style="display:inline-block;background:${accent};color:#fff;text-decoration:none;font-weight:bold;padding:14px 22px;border-radius:8px">동문소식 자세히 보기</a></p></div></div>`;}
function adminNewsStatus_(action,b){const email=verifyAdmin_(b.admin_token),n=findNews_(clean_(b.news_id,40));if(!n)throw new Error('동문소식을 찾을 수 없습니다.');if(action==='adminNewsHide'){n.status='HIDDEN';n.updated_at=now_();const row=n.__row;delete n.__row;updateRow_(SHEETS.NEWS,NEWS_HEADERS,row,n);return{success:true,message:'동문소식이 숨김 처리되었습니다.'};}if(action==='adminNewsPublish'&&n.status==='HIDDEN'){n.status='APPROVED';n.updated_at=now_();const row=n.__row;delete n.__row;updateRow_(SHEETS.NEWS,NEWS_HEADERS,row,n);return{success:true,message:'동문소식이 다시 게시되었습니다.'};}const decision={adminNewsApproveAndMail:'APPROVE_MAIL',adminNewsApprove:'APPROVE_ONLY',adminNewsReject:'REJECTED'}[action];if(!decision)throw new Error('상태 요청이 올바르지 않습니다.');if(n.status!=='PENDING')throw new Error('승인 대기 상태가 아닙니다.');const r=moderateNews_(n,decision,email,'');return{success:true,message:'동문소식 처리 완료'+(r.mailResult?' · 메일 '+r.mailResult.status:'')};}
function adminCreateNews_(b){const email=verifyAdmin_(b.admin_token);validateNews_(b);const target=findAlumni_(clean_(b.target_alumni_id,40));if(!target||target.status!=='APPROVED')throw new Error('소식 대상 졸업생을 찾을 수 없습니다.');const now=now_(),n=Object.assign(newsObject_(b),{news_id:id_('N'),alumni_id:target.alumni_id,submitted_by_alumni_id:'ADMIN:'+email,mail_status:bool_(b.send_mail)?'WAITING':'NOT_REQUESTED',status:'APPROVED',approved_at:now,approved_by:email,created_at:now,updated_at:now,approval_nonce_hash:'',approval_token_expires_at:''});append_(SHEETS.NEWS,NEWS_HEADERS,n);const mail=bool_(b.send_mail)?sendAlumniNewsMail_(n):null;return{success:true,message:'관리자 동문소식이 게시되었습니다.'+(mail?' 메일 '+mail.status:'')};}
function adminSendNewsConsentInvites_(b){const admin=verifyAdmin_(b.admin_token),sentIds=new Set(rows_(SHEETS.NEWS_CONSENT_INVITES,NEWS_CONSENT_INVITE_HEADERS).filter(x=>x.status==='SENT').map(x=>String(x.alumni_id))),targets=rows_(SHEETS.ALUMNI,ALUMNI_HEADERS).filter(x=>x.status==='APPROVED'&&String(x.alumni_news_mail_enabled)===''&&email_(x.email)&&!sentIds.has(String(x.alumni_id)));let sent=0,failed=0;targets.forEach(a=>{try{MailApp.sendEmail({to:String(a.email),subject:'[BigData Alumni] 동문소식 이메일 수신 설정 안내',name:'BigData Alumni Network',htmlBody:newsConsentInviteHtml_(a)});append_(SHEETS.NEWS_CONSENT_INVITES,NEWS_CONSENT_INVITE_HEADERS,{invite_id:id_('NI'),alumni_id:a.alumni_id,sent_at:now_(),status:'SENT'});sent++;}catch(e){failed++;log_('newsConsentInvite','FAILED',a.alumni_id,e.message);}});log_('newsConsentInvites','SUCCESS','',admin+'|sent='+sent+'|failed='+failed);return{success:true,message:'동문소식 수신 설정 안내: 성공 '+sent+'명, 실패 '+failed+'명'};}
function newsConsentInviteHtml_(a){const url=siteUrl_()+'/alumni.html?mode=edit&id='+encodeURIComponent(a.alumni_id),e=html_;return`<div style="font-family:Arial,sans-serif;max-width:620px;margin:auto;color:#243b53"><div style="background:#0b4f7a;color:#fff;padding:24px"><b>BigData Alumni Network</b><h2>동문소식 기능이 새롭게 추가되었습니다.</h2></div><div style="border:1px solid #d9e2ec;padding:24px"><p>${e(a.name)} 동문님, 앞으로 결혼·득남·득녀·부고 등 경조사와 졸업생들의 주요 소식을 확인할 수 있습니다.</p><p>동문소식을 이메일로 받고 싶은 경우 아래 버튼에서 수신 여부를 설정해 주세요.</p><p><a href="${e(url)}" style="display:inline-block;background:#1477b8;color:#fff;text-decoration:none;font-weight:bold;padding:14px 22px;border-radius:8px">동문소식 이메일 수신 설정</a></p><p style="color:#627d98;font-size:13px">수신을 원하지 않으면 아무 조치를 하지 않아도 이메일이 발송되지 않습니다.</p></div></div>`;}
