'use strict';
const SHEETS={ALUMNI:'alumni',CONTACTS:'contact_requests',ADMINS:'admins',LOGS:'logs'};
const ALUMNI_HEADERS=['alumni_id','name','student_id','graduation_year','email','phone','employment_status','company','job','company_url','employment_year','job_description','skills','bachelor_status','bachelor_school','bachelor_major','bachelor_year','graduate_status','graduate_school_type','graduate_school','graduate_major','graduate_degree','graduate_entry_year','graduate_graduation_year','research_fields','mentoring_topics','introduction','message_to_juniors','contact_allowed','edit_pin_hash','status','created_at','updated_at'];
const CONTACT_HEADERS=['request_id','alumni_id','requester_name','requester_type','requester_student_id_or_year','requester_email','requester_phone','share_email','share_phone','category','subject','message','status','created_at','sent_at'];
const ADMIN_HEADERS=['email','status','created_at'];
const LOG_HEADERS=['log_id','action','result','reference_id','detail','created_at'];
const PUBLIC_FIELDS=['alumni_id','name','graduation_year','employment_status','company','job','company_url','employment_year','job_description','skills','bachelor_status','bachelor_school','bachelor_major','bachelor_year','graduate_status','graduate_school_type','graduate_school','graduate_major','graduate_degree','graduate_entry_year','graduate_graduation_year','research_fields','mentoring_topics','introduction','message_to_juniors','contact_allowed','updated_at'];
const ENUMS={employment_status:['취업 중','대학원 준비중','대학원 연구실(석사과정)','대학원 연구실(박사과정)','구직 중','미취업','기타'],bachelor_status:['재학','취득','취득 예정','미취득'],graduate_status:['진학하지 않음','진학 예정(준비중)','재학','휴학','수료','졸업'],graduate_school_type:['일반대학원','전문대학원','특수대학원'],graduate_degree:['','석사','박사','석박사통합'],requester_type:['재학생','졸업생']};

function doGet(e){try{return respond_(routeGet_(String((e.parameter||{}).action||''),e.parameter||{}));}catch(err){log_('get','FAILED','',err.message);return respond_({success:false,message:safeError_(err)});}}
function doPost(e){let body={};try{body=JSON.parse((e.postData&&e.postData.contents)||'{}');return respond_(routePost_(String(body.action||''),body));}catch(err){log_('post','FAILED','',err.message);return respond_({success:false,message:safeError_(err)});}}
function routeGet_(action,p){if(action==='list')return {success:true,data:listPublic_()};if(action==='detail')return {success:true,data:detailPublic_(p.id)};throw new Error('지원하지 않는 요청입니다.');}
function routePost_(action,b){if(action==='register')return register_(b);if(action==='getOwn')return getOwn_(b);if(action==='update')return update_(b);if(action==='contact')return contact_(b);if(action==='adminList')return adminList_(b);if(['adminApprove','adminReject','adminHide'].indexOf(action)>=0)return adminStatus_(action,b);throw new Error('지원하지 않는 요청입니다.');}
function respond_(obj){return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON);}
function safeError_(e){const allowed=['지원하지','찾을 수','입력','형식','필수','PIN','권한','요청','허용','중복','길이','동의','설정'];return allowed.some(x=>String(e.message).includes(x))?e.message:'처리 중 오류가 발생했습니다.';}

function setup(){const ss=db_();ensure_(ss,SHEETS.ALUMNI,ALUMNI_HEADERS);ensure_(ss,SHEETS.CONTACTS,CONTACT_HEADERS);ensure_(ss,SHEETS.ADMINS,ADMIN_HEADERS);ensure_(ss,SHEETS.LOGS,LOG_HEADERS);const props=PropertiesService.getScriptProperties();if(!props.getProperty('PIN_PEPPER'))props.setProperty('PIN_PEPPER',Utilities.getUuid()+Utilities.getUuid());}
function ensure_(ss,name,headers){let sh=ss.getSheetByName(name);if(!sh)sh=ss.insertSheet(name);if(sh.getLastRow()===0)sh.appendRow(headers);const got=sh.getRange(1,1,1,headers.length).getValues()[0];if(headers.some((h,i)=>got[i]!==h))throw new Error(name+' 시트 헤더가 README 구조와 다릅니다.');sh.setFrozenRows(1);}
function db_(){const id=PropertiesService.getScriptProperties().getProperty('SPREADSHEET_ID');if(!id)throw new Error('SPREADSHEET_ID 설정이 필요합니다.');return SpreadsheetApp.openById(id);}
function sheet_(name){const sh=db_().getSheetByName(name);if(!sh)throw new Error('데이터 저장소가 설정되지 않았습니다. setup을 실행해 주세요.');return sh;}
function rows_(name,headers){const sh=sheet_(name);if(sh.getLastRow()<2)return[];return sh.getRange(2,1,sh.getLastRow()-1,headers.length).getValues().map((r,i)=>Object.assign({__row:i+2},Object.fromEntries(headers.map((h,j)=>[h,r[j]]))));}
function prepareTextColumns_(sh,headers,row){['phone','requester_phone'].forEach(k=>{const i=headers.indexOf(k);if(i>=0)sh.getRange(row,i+1).setNumberFormat('@');});}
function append_(name,headers,obj){const sh=sheet_(name),row=sh.getLastRow()+1;prepareTextColumns_(sh,headers,row);sh.getRange(row,1,1,headers.length).setValues([headers.map(h=>obj[h]===undefined?'':obj[h])]);}
function updateRow_(name,headers,row,obj){const sh=sheet_(name);prepareTextColumns_(sh,headers,row);sh.getRange(row,1,1,headers.length).setValues([headers.map(h=>obj[h]===undefined?'':obj[h])]);}
function now_(){return Utilities.formatDate(new Date(),'Asia/Seoul',"yyyy-MM-dd'T'HH:mm:ssXXX");}
function id_(prefix){return prefix+'-'+Utilities.formatDate(new Date(),'Asia/Seoul','yyyyMMdd')+'-'+Utilities.getUuid().slice(0,8).toUpperCase();}
function findAlumni_(id){return rows_(SHEETS.ALUMNI,ALUMNI_HEADERS).find(x=>String(x.alumni_id)===String(id));}
function public_(x){return Object.fromEntries(PUBLIC_FIELDS.map(k=>[k,normalizeOut_(k,x[k])]));}
function normalizeOut_(key,v){if(['skills','research_fields','mentoring_topics'].includes(key))return String(v||'').split('|').filter(Boolean);if(key==='contact_allowed')return String(v).toLowerCase()==='true';if(v instanceof Date)return Utilities.formatDate(v,'Asia/Seoul',"yyyy-MM-dd'T'HH:mm:ssXXX");return v===undefined?'':v;}
function listPublic_(){return rows_(SHEETS.ALUMNI,ALUMNI_HEADERS).filter(x=>x.status==='APPROVED').map(public_);}
function detailPublic_(id){const x=findAlumni_(clean_(id,40));if(!x||x.status!=='APPROVED')throw new Error('졸업생 정보를 찾을 수 없습니다.');return public_(x);}

function register_(b){validateAlumni_(b,true);const lock=LockService.getScriptLock();lock.waitLock(10000);try{const now=now_(),id=id_('A'),obj=alumniObject_(b);Object.assign(obj,{alumni_id:id,edit_pin_hash:hashPin_(id,b.edit_pin),status:'PENDING',created_at:now,updated_at:now});append_(SHEETS.ALUMNI,ALUMNI_HEADERS,obj);log_('register','SUCCESS',id,'PENDING');return{success:true,message:'정보 등록이 완료되었습니다. 관리자 확인 후 공개됩니다.',alumni_id:id};}finally{lock.releaseLock();}}
function getOwn_(b){const id=clean_(b.alumni_id,40),x=findAlumni_(id);if(!x||!verifyPin_(id,b.edit_pin,x.edit_pin_hash))throw new Error('Alumni ID 또는 PIN이 올바르지 않습니다.');const out=Object.fromEntries(ALUMNI_HEADERS.filter(k=>!['edit_pin_hash'].includes(k)).map(k=>[k,normalizeOut_(k,x[k])]));return{success:true,data:out};}
function update_(b){validateAlumni_(b,false);const id=clean_(b.alumni_id,40),lock=LockService.getScriptLock();lock.waitLock(10000);try{const x=findAlumni_(id);if(!x||!verifyPin_(id,b.auth_pin,x.edit_pin_hash))throw new Error('Alumni ID 또는 PIN이 올바르지 않습니다.');const obj=Object.assign({},x,alumniObject_(b),{alumni_id:id,edit_pin_hash:x.edit_pin_hash,status:'PENDING',created_at:x.created_at,updated_at:now_()});if(b.edit_pin)obj.edit_pin_hash=hashPin_(id,b.edit_pin);delete obj.__row;updateRow_(SHEETS.ALUMNI,ALUMNI_HEADERS,x.__row,obj);log_('update','SUCCESS',id,'PENDING');return{success:true,message:'정보가 수정되었습니다. 관리자 재승인 후 공개됩니다.'};}finally{lock.releaseLock();}}
function alumniObject_(b){const obj={};ALUMNI_HEADERS.forEach(k=>{if(['alumni_id','edit_pin_hash','status','created_at','updated_at'].includes(k))return;obj[k]=['skills','research_fields','mentoring_topics'].includes(k)?list_(b[k],300):clean_(b[k],limit_(k));});obj.phone=phoneText_(obj.phone);obj.contact_allowed=bool_(b.contact_allowed);if(!['취업 중','대학원 연구실(석사과정)','대학원 연구실(박사과정)'].includes(obj.employment_status)){['company','job','company_url','employment_year','job_description','skills'].forEach(k=>obj[k]='');}if(obj.bachelor_status==='미취득'){['bachelor_school','bachelor_major','bachelor_year'].forEach(k=>obj[k]='');}if(['진학하지 않음','진학 예정(준비중)'].includes(obj.graduate_status)){['graduate_school_type','graduate_school','graduate_major','graduate_degree','graduate_entry_year','graduate_graduation_year','research_fields'].forEach(k=>obj[k]='');}return obj;}
function validateAlumni_(b,isNew){required_(b,['name','graduation_year','email','phone','employment_status','bachelor_status','graduate_status','contact_allowed']);if(!email_(b.email))throw new Error('이메일 형식을 확인해 주세요.');if(!phone_(b.phone))throw new Error('휴대전화 형식을 확인해 주세요.');enum_(b,'employment_status');enum_(b,'bachelor_status');enum_(b,'graduate_status');if(['취업 중','대학원 연구실(석사과정)','대학원 연구실(박사과정)'].includes(b.employment_status))required_(b,['company','job']);if(['재학','휴학','수료','졸업'].includes(b.graduate_status)){required_(b,['graduate_school_type','graduate_school','graduate_major']);enum_(b,'graduate_school_type');if(b.graduate_degree)enum_(b,'graduate_degree');}if(bool_(b.contact_allowed)&&!list_(b.mentoring_topics,300))throw new Error('연락 요청을 허용하려면 상담 가능 분야를 1개 이상 선택해 주세요.');if(!bool_(b.privacy_consent)||!bool_(b.identity_consent))throw new Error('필수 개인정보 동의가 필요합니다.');if(bool_(b.contact_allowed)&&!bool_(b.contact_consent))throw new Error('연락 요청 수신 동의가 필요합니다.');if((isNew||b.edit_pin)&&!/^\d{6,12}$/.test(String(b.edit_pin||'')))throw new Error('PIN은 숫자 6~12자리여야 합니다.');}

function contact_(b){required_(b,['alumni_id','requester_name','requester_type','requester_email','category','subject','message']);if(b.website)throw new Error('요청을 처리할 수 없습니다.');if(!email_(b.requester_email))throw new Error('이메일 형식을 확인해 주세요.');if(b.requester_phone&&!phone_(b.requester_phone))throw new Error('휴대전화 형식을 확인해 주세요.');enum_(b,'requester_type');if(String(b.message).trim().length<20)throw new Error('문의 내용은 20자 이상 입력해 주세요.');if(bool_(b.share_phone)&&!b.requester_phone)throw new Error('전달할 휴대전화를 입력해 주세요.');const alum=findAlumni_(clean_(b.alumni_id,40));if(!alum||alum.status!=='APPROVED'||!bool_(alum.contact_allowed))throw new Error('현재 연락 요청을 허용하지 않는 졸업생입니다.');rateLimit_(alum.alumni_id,b.requester_email);const lock=LockService.getScriptLock();lock.waitLock(10000);const now=now_(),rid=id_('R'),obj={request_id:rid,alumni_id:alum.alumni_id,requester_name:clean_(b.requester_name,40),requester_type:clean_(b.requester_type,10),requester_student_id_or_year:clean_(b.requester_student_id_or_year,30),requester_email:clean_(b.requester_email,120),requester_phone:phoneText_(b.requester_phone),share_email:bool_(b.share_email),share_phone:bool_(b.share_phone),category:clean_(b.category,40),subject:clean_(b.subject,100),message:clean_(b.message,1500),status:'PENDING',created_at:now,sent_at:''};append_(SHEETS.CONTACTS,CONTACT_HEADERS,obj);lock.releaseLock();try{MailApp.sendEmail({to:String(alum.email),subject:'[BigData Alumni] 후배의 연락 요청이 도착했습니다',htmlBody:mailHtml_(alum,obj),name:'BigData Alumni Network'});obj.status='SENT';obj.sent_at=now_();updateContact_(rid,obj);log_('contact','SUCCESS',rid,alum.alumni_id);return{success:true,message:'연락 요청이 정상적으로 전달되었습니다.'};}catch(e){obj.status='FAILED';updateContact_(rid,obj);log_('contact','FAILED',rid,e.message);throw new Error('메일 발송 중 오류가 발생했습니다. 잠시 후 다시 시도해 주세요.');}}
function rateLimit_(aid,email){const key=Utilities.base64EncodeWebSafe(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,aid+'|'+String(email).toLowerCase())).slice(0,80),cache=CacheService.getScriptCache();if(cache.get(key))throw new Error('동일한 선배에게 짧은 시간 내 중복 요청할 수 없습니다.');const cutoff=Date.now()-30*60*1000,dup=rows_(SHEETS.CONTACTS,CONTACT_HEADERS).some(x=>x.alumni_id===aid&&String(x.requester_email).toLowerCase()===String(email).toLowerCase()&&new Date(x.created_at).getTime()>cutoff);if(dup)throw new Error('동일한 선배에게 짧은 시간 내 중복 요청할 수 없습니다.');cache.put(key,'1',1800);}
function updateContact_(id,obj){const x=rows_(SHEETS.CONTACTS,CONTACT_HEADERS).find(r=>r.request_id===id);if(x)updateRow_(SHEETS.CONTACTS,CONTACT_HEADERS,x.__row,obj);}
function mailHtml_(a,r){const e=html_;let contacts=[];if(r.share_email)contacts.push('이메일: '+e(r.requester_email));if(r.share_phone)contacts.push('휴대전화: '+e(r.requester_phone));return `<div style="font-family:Arial,sans-serif;max-width:640px;color:#243b53"><h2 style="color:#102a43">BigData Alumni Network</h2><p>안녕하세요. ${e(a.name)} 졸업생님.</p><p>한국폴리텍대학 서울강서캠퍼스 빅데이터소프트웨어공학과 Alumni Network를 통해 연락 요청이 접수되었습니다.</p><div style="background:#f3f7fa;padding:16px;border-radius:10px"><b>요청자 정보</b><p>${e(r.requester_name)} · ${e(r.requester_type)}<br>${e(r.requester_student_id_or_year)}</p><b>문의 분야</b><p>${e(r.category)}</p><b>문의 제목</b><p>${e(r.subject)}</p><b>문의 내용</b><p style="white-space:pre-wrap">${e(r.message)}</p><b>연락처</b><p>${contacts.length?contacts.join('<br>'):'공개를 선택한 연락처가 없습니다.'}</p></div><p style="font-size:12px;color:#627d98">본 메일은 한국폴리텍대학 서울강서캠퍼스 빅데이터소프트웨어공학과 BigData Alumni Network를 통해 자동 발송되었습니다.</p></div>`;}

function adminList_(b){const email=verifyAdmin_(b.admin_token);const view=b.view==='requests'?'requests':'alumni';log_('adminList','SUCCESS',email,view);if(view==='requests')return{success:true,data:rows_(SHEETS.CONTACTS,CONTACT_HEADERS).map(x=>{delete x.__row;delete x.requester_email;delete x.requester_phone;delete x.message;return x;})};return{success:true,data:rows_(SHEETS.ALUMNI,ALUMNI_HEADERS).map(x=>{const safe=public_(x);safe.email=String(x.email||'');safe.phone=String(x.phone||'');safe.status=x.status;safe.created_at=normalizeOut_('',x.created_at);return safe;})};}
function adminStatus_(action,b){const email=verifyAdmin_(b.admin_token),map={adminApprove:'APPROVED',adminReject:'REJECTED',adminHide:'HIDDEN'},x=findAlumni_(clean_(b.alumni_id,40));if(!x)throw new Error('졸업생 정보를 찾을 수 없습니다.');x.status=map[action];x.updated_at=now_();const row=x.__row;delete x.__row;updateRow_(SHEETS.ALUMNI,ALUMNI_HEADERS,row,x);log_(action,'SUCCESS',x.alumni_id,email);return{success:true,message:'상태가 변경되었습니다.'};}
function verifyAdmin_(token){if(!token)throw new Error('관리자 권한이 필요합니다.');const client=PropertiesService.getScriptProperties().getProperty('GOOGLE_CLIENT_ID');if(!client)throw new Error('관리자 인증 설정이 필요합니다.');let info;try{const res=UrlFetchApp.fetch('https://oauth2.googleapis.com/tokeninfo?id_token='+encodeURIComponent(token),{muteHttpExceptions:true});info=JSON.parse(res.getContentText());}catch(e){throw new Error('관리자 인증에 실패했습니다.');}if(info.aud!==client||!['accounts.google.com','https://accounts.google.com'].includes(info.iss)||info.email_verified!=='true')throw new Error('관리자 권한이 없습니다.');const ok=rows_(SHEETS.ADMINS,ADMIN_HEADERS).some(x=>String(x.email).toLowerCase()===String(info.email).toLowerCase()&&x.status==='ACTIVE');if(!ok)throw new Error('관리자 권한이 없습니다.');return info.email;}

function hashPin_(id,pin){const pepper=PropertiesService.getScriptProperties().getProperty('PIN_PEPPER');if(!pepper)throw new Error('PIN 보안 설정이 필요합니다. setup을 실행해 주세요.');return Utilities.base64EncodeWebSafe(Utilities.computeHmacSha256Signature(id+'|'+pin,pepper));}
function verifyPin_(id,pin,hash){return /^\d{6,12}$/.test(String(pin||''))&&hashPin_(id,pin)===String(hash);}
function log_(action,result,ref,detail){try{append_(SHEETS.LOGS,LOG_HEADERS,{log_id:id_('L'),action,result,reference_id:ref,detail:clean_(detail,500),created_at:now_()});}catch(_){}}
function required_(b,ks){ks.forEach(k=>{if(b[k]===undefined||b[k]===null||String(b[k]).trim()==='')throw new Error(k+' 필수 입력값을 확인해 주세요.');});}
function enum_(b,k){if(!ENUMS[k].includes(String(b[k])))throw new Error(k+' 입력값이 올바르지 않습니다.');}
function clean_(v,max){let s=String(v===undefined||v===null?'':v).replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,'').trim().slice(0,max||500);return /^[=+@]|^-[^0-9]/.test(s)?"'"+s:s;}
function list_(v,max){const a=Array.isArray(v)?v:String(v||'').split(/[|,]/);return a.map(x=>clean_(x,60)).filter(Boolean).slice(0,20).join('|').slice(0,max||300);}
function bool_(v){return v===true||String(v).toLowerCase()==='true';}
function phoneText_(v){const s=clean_(v,20);return /^\d{9,10}$/.test(s)&&s.charAt(0)!=='0'?'0'+s:s;}
function email_(v){return /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(String(v||''))&&String(v).length<=120;}
function phone_(v){return /^[0-9+()\-\s]{8,20}$/.test(String(v||''));}
function limit_(k){return ({name:40,email:120,phone:20,company_url:300,job_description:500,introduction:500,message_to_juniors:500}[k]||100);}
function html_(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}

function repairPhoneLeadingZeros(){[[SHEETS.ALUMNI,ALUMNI_HEADERS,'phone'],[SHEETS.CONTACTS,CONTACT_HEADERS,'requester_phone']].forEach(([name,headers,key])=>{const sh=sheet_(name),col=headers.indexOf(key)+1,last=sh.getLastRow();if(last<2||col<1)return;const range=sh.getRange(2,col,last-1,1),values=range.getDisplayValues().map(([v])=>[phoneText_(v)]);range.setNumberFormat('@');range.setValues(values);});}
